import { create } from "zustand";
import {
  CompletarInvitacionCliente,
  ActualizarWhatsappMensaje,
  CrearWhatsappMensaje,
  DespacharWhatsappMensaje,
  EditarCrmCliente,
  EditarWhatsappPlantilla,
  EnviarInvitacionCliente,
  InsertarCargo,
  InsertarCrmAsistencia,
  InsertarCrmCliente,
  InsertarCrmHorario,
  InsertarCrmPago,
  InsertarCrmPlan,
  InsertarCrmSuscripcion,
  InsertarTrabajador,
  MostrarCrmData,
  MostrarInvitacionClienteActual,
  UpsertCrmAutomatizacion,
  UpsertEmpresaModulo,
  UpsertRolModulo,
  UpsertWhatsappConfig,
} from "../supabase/crudCrm";

const initialState = {
  clientes: [],
  planes: [],
  horarios: [],
  invitaciones: [],
  suscripciones: [],
  pagos: [],
  asistencias: [],
  cargos: [],
  trabajadores: [],
  empresaModulos: [],
  rolModulos: [],
  modulos: [],
  roles: [],
  resumen: null,
  whatsappConfig: null,
  whatsappPlantillas: [],
  whatsappMensajes: [],
  automatizaciones: [],
};

export const useCrmStore = create((set) => ({
  ...initialState,
  cargarCrm: async (payload) => {
    const data = await MostrarCrmData(payload);
    set(data);
    return data;
  },
  insertarCliente: (payload) => InsertarCrmCliente(payload),
  editarCliente: (payload) => EditarCrmCliente(payload),
  enviarInvitacion: (payload) => EnviarInvitacionCliente(payload),
  insertarPlan: (payload) => InsertarCrmPlan(payload),
  insertarHorario: (payload) => InsertarCrmHorario(payload),
  insertarSuscripcion: (payload) => InsertarCrmSuscripcion(payload),
  insertarPago: (payload) => InsertarCrmPago(payload),
  insertarAsistencia: (payload) => InsertarCrmAsistencia(payload),
  insertarCargo: (payload) => InsertarCargo(payload),
  insertarTrabajador: (payload) => InsertarTrabajador(payload),
  upsertEmpresaModulo: (payload) => UpsertEmpresaModulo(payload),
  upsertRolModulo: (payload) => UpsertRolModulo(payload),
  upsertWhatsappConfig: (payload) => UpsertWhatsappConfig(payload),
  editarWhatsappPlantilla: (payload) => EditarWhatsappPlantilla(payload),
  crearWhatsappMensaje: (payload) => CrearWhatsappMensaje(payload),
  actualizarWhatsappMensaje: (payload) => ActualizarWhatsappMensaje(payload),
  despacharWhatsappMensaje: (payload) => DespacharWhatsappMensaje(payload),
  upsertCrmAutomatizacion: (payload) => UpsertCrmAutomatizacion(payload),
  mostrarInvitacionActual: () => MostrarInvitacionClienteActual(),
  completarInvitacion: (payload) => CompletarInvitacionCliente(payload),
}));
