-- Transactional CRM notifications for email and WhatsApp.
-- The scheduler calls an Edge Function with a per-project secret kept in Vault;
-- no SMTP, Meta or service-role credential is exposed through the Data API.

create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;
create extension if not exists supabase_vault with schema vault;

alter table public.clientes_crm
  add column if not exists notificaciones_email boolean not null default true,
  add column if not exists notificaciones_whatsapp boolean not null default true;

comment on column public.clientes_crm.notificaciones_email is
  'Preferencia para avisos transaccionales por correo; false respeta la baja del cliente.';
comment on column public.clientes_crm.notificaciones_whatsapp is
  'Preferencia para avisos transaccionales por WhatsApp; false respeta la baja del cliente.';

alter table public.crm_whatsapp_mensajes
  add column if not exists dedupe_key text;

create unique index if not exists crm_whatsapp_mensajes_empresa_dedupe_uidx
  on public.crm_whatsapp_mensajes (id_empresa, dedupe_key);

create table if not exists public.crm_notificacion_envios (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  id_cliente_crm bigint references public.clientes_crm(id) on delete set null,
  id_pago bigint references public.crm_pagos(id) on delete set null,
  id_suscripcion bigint references public.crm_suscripciones(id) on delete set null,
  evento text not null
    check (evento in ('cliente_creado', 'pago_vencido', 'factura_emitida', 'suscripcion_por_vencer')),
  canal text not null check (canal in ('email', 'whatsapp')),
  destino text not null,
  asunto text,
  cuerpo text not null,
  dedupe_key text not null,
  estado text not null default 'pendiente'
    check (estado in ('pendiente', 'enviado', 'error', 'omitido')),
  intentos smallint not null default 0 check (intentos between 0 and 10),
  provider_message_id text,
  scheduled_at timestamptz not null default now(),
  last_attempt_at timestamptz,
  sent_at timestamptz,
  error text,
  detalles jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_empresa, canal, dedupe_key)
);

create index if not exists crm_notificacion_envios_empresa_estado_idx
  on public.crm_notificacion_envios (id_empresa, estado, created_at desc);
create index if not exists crm_notificacion_envios_retry_idx
  on public.crm_notificacion_envios (estado, scheduled_at)
  where estado in ('pendiente', 'error');

drop trigger if exists trg_crm_notificacion_envios_updated_at
on public.crm_notificacion_envios;
create trigger trg_crm_notificacion_envios_updated_at
before update on public.crm_notificacion_envios
for each row execute function private.set_updated_at();

alter table public.crm_notificacion_envios enable row level security;

drop policy if exists "crm_notificacion_envios_company_select"
on public.crm_notificacion_envios;
create policy "crm_notificacion_envios_company_select"
on public.crm_notificacion_envios
for select to authenticated
using (id_empresa = (select private.current_empresa_id()));

revoke all on public.crm_notificacion_envios from public, anon;
revoke all on sequence public.crm_notificacion_envios_id_seq from public, anon, authenticated;
grant select on public.crm_notificacion_envios to authenticated;

alter table public.crm_automatizaciones
  drop constraint if exists crm_automatizaciones_dias_antes_check;
alter table public.crm_automatizaciones
  add constraint crm_automatizaciones_dias_antes_check
  check (dias_antes between 0 and 90);

-- Enable the four useful transactional communications on both channels.
-- Existing tenant choices are preserved by ON CONFLICT DO NOTHING.
insert into public.crm_automatizaciones (
  id_empresa,
  evento,
  canal,
  tipo_mensaje,
  dias_antes,
  activo
)
select
  company.id,
  automation.evento,
  channel.canal,
  automation.tipo_mensaje,
  automation.dias_antes,
  true
from public.empresa company
cross join (
  values
    ('cliente_creado', 'bienvenida', 0),
    ('pago_vencido', 'cobro', 0),
    ('factura_emitida', 'factura', 0),
    ('suscripcion_por_vencer', 'suscripcion_por_vencer', 7)
) as automation(evento, tipo_mensaje, dias_antes)
cross join (values ('email'), ('whatsapp')) as channel(canal)
on conflict (id_empresa, evento, canal) do nothing;

-- Keep the latest directory contract and append communication preferences.
create or replace view public.crm_clientes_directorio
with (security_invoker = true)
as
select
  c.id,
  c.public_id,
  c.id_empresa,
  c.codigo,
  c.id_cliente_proveedor,
  c.id_auth,
  c.nombres,
  c.apellidos,
  c.email,
  c.telefono,
  c.direccion,
  c.identificador_nacional,
  c.identificador_fiscal,
  c.estado as estado_cliente,
  c.origen,
  c.id_horario,
  c.created_at,
  c.updated_at,
  subscription.id as id_suscripcion,
  subscription.id_plan,
  subscription.estado as estado_suscripcion,
  subscription.fecha_inicio,
  subscription.fecha_fin,
  subscription.precio_pactado,
  plan.nombre as plan_nombre,
  plan.periodicidad as plan_periodicidad,
  plan.duracion_dias as plan_duracion_dias,
  schedule.nombre as horario_nombre,
  coalesce(overdue.saldo_vencido, 0) as saldo_vencido,
  coalesce(overdue.pagos_pendientes, 0) as pagos_pendientes,
  last_payment.ultimo_pago_at,
  last_payment.ultimo_pago_monto,
  case
    when c.estado in ('inactivo', 'suspendido') then 'inactiva'
    when coalesce(overdue.saldo_vencido, 0) > 0
      or subscription.estado = 'vencida'
      or (subscription.estado = 'activa' and subscription.fecha_fin < current_date
          and coalesce(balance.saldo_pendiente, subscription.precio_pactado, 0) > 0) then 'moroso'
    when subscription.id is null then 'sin_suscripcion'
    when subscription.estado <> 'activa' then 'inactiva'
    when coalesce(balance.estado_pago, 'pendiente') = 'parcial' then 'pago_parcial'
    when coalesce(balance.estado_pago, 'pendiente') = 'pendiente' then 'pendiente_pago'
    when subscription.fecha_fin <= current_date + 7 then 'por_vencer'
    else 'al_dia'
  end as estado_financiero,
  case when subscription.id is not null then subscription.fecha_fin - current_date else null end as dias_para_vencer,
  lower(concat_ws(' ', c.codigo, c.nombres, c.apellidos, c.email, c.telefono, plan.nombre)) as busqueda,
  coalesce(balance.total_plan, subscription.precio_pactado, plan.precio, 0)::numeric(12,2) as total_plan,
  coalesce(balance.abonado_periodo, 0)::numeric(12,2) as abonado_plan,
  coalesce(balance.saldo_pendiente, subscription.precio_pactado, plan.precio, 0)::numeric(12,2) as saldo_plan,
  coalesce(balance.estado_pago, case when subscription.id is null then null else 'pendiente' end) as estado_pago_plan,
  c.notificaciones_email,
  c.notificaciones_whatsapp
from public.clientes_crm c
left join lateral (
  select candidate.*
  from public.crm_suscripciones candidate
  where candidate.id_empresa = c.id_empresa
    and candidate.id_cliente_crm = c.id
  order by
    case candidate.estado when 'activa' then 0 when 'pausada' then 1 when 'vencida' then 2 else 3 end,
    candidate.fecha_fin desc,
    candidate.id desc
  limit 1
) subscription on true
left join public.crm_planes plan on plan.id = subscription.id_plan
left join public.crm_horarios schedule on schedule.id = c.id_horario
left join public.crm_suscripciones_saldos balance on balance.id = subscription.id
left join lateral (
  select
    coalesce(sum(payment.monto) filter (
      where payment.estado = 'vencido'
        or (payment.estado = 'pendiente' and payment.fecha_vencimiento < current_date)
    ), 0) as saldo_vencido,
    count(*) filter (
      where payment.estado = 'vencido'
        or (payment.estado = 'pendiente' and payment.fecha_vencimiento < current_date)
    ) as pagos_pendientes
  from public.crm_pagos payment
  where payment.id_empresa = c.id_empresa
    and payment.id_cliente_crm = c.id
) overdue on true
left join lateral (
  select payment.fecha_pago as ultimo_pago_at, payment.monto as ultimo_pago_monto
  from public.crm_pagos payment
  where payment.id_empresa = c.id_empresa
    and payment.id_cliente_crm = c.id
    and payment.estado = 'pagado'
  order by payment.fecha_pago desc nulls last, payment.created_at desc, payment.id desc
  limit 1
) last_payment on true;

revoke all on public.crm_clientes_directorio from public, anon;
grant select on public.crm_clientes_directorio to authenticated;

-- Only the Edge Function's service role may validate the encrypted scheduler
-- secret. The function is immediately revoked from PUBLIC because it is in an
-- exposed schema.
create or replace function public.crm_verify_notification_cron_secret(p_secret text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select coalesce(
    p_secret = (
      select secret.decrypted_secret
      from vault.decrypted_secrets secret
      where secret.name = 'crm_notifications_cron_secret'
      limit 1
    ),
    false
  )
$function$;

revoke all on function public.crm_verify_notification_cron_secret(text)
from public, anon, authenticated;
grant execute on function public.crm_verify_notification_cron_secret(text)
to service_role;

do $block$
begin
  if not exists (
    select 1 from vault.secrets where name = 'crm_notifications_cron_secret'
  ) then
    perform vault.create_secret(
      encode(extensions.gen_random_bytes(32), 'hex'),
      'crm_notifications_cron_secret',
      'Authenticates the daily CRM notification Edge Function call.'
    );
  end if;
end;
$block$;

do $block$
declare
  existing_job bigint;
begin
  for existing_job in
    select jobid from cron.job where jobname = 'crm-notifications-daily'
  loop
    perform cron.unschedule(existing_job);
  end loop;
end;
$block$;

select cron.schedule(
  'crm-notifications-daily',
  '0 13 * * *',
  $cron$
    select net.http_post(
      url := 'https://cqnfziultbkobdkegtfm.supabase.co/functions/v1/crm-notifications-run',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'X-CRM-Cron-Secret', (
          select secret.decrypted_secret
          from vault.decrypted_secrets secret
          where secret.name = 'crm_notifications_cron_secret'
          limit 1
        )
      ),
      body := jsonb_build_object('source', 'pg_cron')
    ) as request_id;
  $cron$
);

do $block$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'crm_notificacion_envios'
    ) then
    alter publication supabase_realtime
      add table public.crm_notificacion_envios;
  end if;
end;
$block$;

notify pgrst, 'reload schema';
