-- Secure invitation lookup for authenticated recipients. Invited clients are
-- not staff members yet, so they cannot read the administration table directly.
create or replace function private.crm_obtener_invitacion_actual_impl(
  p_invitacion_id uuid default null
)
returns table (
  id uuid,
  id_empresa bigint,
  email text,
  id_plan bigint,
  expires_at timestamptz,
  plan_nombre text,
  plan_descripcion text,
  plan_periodicidad text,
  plan_duracion_dias integer,
  plan_precio numeric
)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_auth_id uuid := (select auth.uid());
  v_auth_email text := lower(nullif((select auth.jwt() ->> 'email'), ''));
begin
  if v_auth_id is null or v_auth_email is null then
    raise exception 'Debes abrir la invitación desde el enlace recibido';
  end if;

  return query
  select
    invitation.id,
    invitation.id_empresa,
    invitation.email,
    invitation.id_plan,
    invitation.expires_at,
    plan.nombre,
    plan.descripcion,
    plan.periodicidad,
    plan.duracion_dias,
    plan.precio
  from public.crm_invitaciones invitation
  join public.crm_planes plan
    on plan.id = invitation.id_plan
   and plan.id_empresa = invitation.id_empresa
  where invitation.estado = 'pendiente'
    and invitation.expires_at > now()
    and lower(invitation.email) = v_auth_email
    and (p_invitacion_id is null or invitation.id = p_invitacion_id)
  order by invitation.created_at desc
  limit 1;
end;
$function$;

revoke all on function private.crm_obtener_invitacion_actual_impl(uuid) from public, anon;
grant execute on function private.crm_obtener_invitacion_actual_impl(uuid) to authenticated;

create or replace function public.crm_obtener_invitacion_actual(
  p_invitacion_id uuid default null
)
returns table (
  id uuid,
  id_empresa bigint,
  email text,
  id_plan bigint,
  expires_at timestamptz,
  plan_nombre text,
  plan_descripcion text,
  plan_periodicidad text,
  plan_duracion_dias integer,
  plan_precio numeric
)
language sql
security invoker
set search_path = ''
as $function$
  select * from private.crm_obtener_invitacion_actual_impl(p_invitacion_id)
$function$;

revoke all on function public.crm_obtener_invitacion_actual(uuid) from public, anon;
grant execute on function public.crm_obtener_invitacion_actual(uuid) to authenticated;

-- Keeps a minimal audit trail for a receipt sent from the CRM. The table is
-- deliberately inaccessible from the client; only the trusted Edge Function
-- writes it after validating the caller and tenant.
create table if not exists public.crm_comprobante_email_envios (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  comprobante_id text not null,
  correo_destino text not null,
  enviado_por bigint references public.usuarios(id) on delete set null,
  enviado_at timestamptz not null default now(),
  estado text not null default 'enviado' check (estado in ('enviado', 'error')),
  detalle_error text,
  created_at timestamptz not null default now()
);

create index if not exists crm_comprobante_email_envios_empresa_comprobante_idx
  on public.crm_comprobante_email_envios (id_empresa, comprobante_id, enviado_at desc);

alter table public.crm_comprobante_email_envios enable row level security;
revoke all on public.crm_comprobante_email_envios from public, anon, authenticated;

-- CRM screens use Postgres Changes, which honors the existing tenant RLS
-- policies. This avoids a second socket server and never broadcasts data
-- across companies.
do $block$
declare
  target_table text;
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    foreach target_table in array array[
      'crm_invitaciones',
      'crm_horarios',
      'clientes_crm',
      'crm_suscripciones',
      'crm_pagos',
      'crm_comprobantes_cobro',
      'crm_asistencias'
    ] loop
      if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = target_table
      ) then
        execute format('alter publication supabase_realtime add table public.%I', target_table);
      end if;
    end loop;
  end if;
end;
$block$;

notify pgrst, 'reload schema';
