-- ActiveSelfControl: CRM Data API exposure, WhatsApp messaging queue, and legacy POS aliases.
-- Supabase changed new-project defaults so public tables are not always exposed to
-- Data API roles automatically. Keep explicit GRANTs + RLS for every table used
-- directly by the React client.

create or replace function private.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Legacy code still asks the REST API for `almacen` and `stock`. The actual
-- imported table is `almacenes`, so expose security-invoker compatibility views.
drop view if exists public.stock;
drop view if exists public.almacen;

create or replace view public.almacen
with (security_invoker = true)
as
select
  a.id,
  a.id_sucursal,
  a.id_producto,
  coalesce(p.nombre, s.nombre, 'Almacen principal') as nombre,
  a.stock,
  a.stock_minimo
from public.almacenes a
left join public.productos p on p.id = a.id_producto
left join public.sucursales s on s.id = a.id_sucursal;

create or replace view public.stock
with (security_invoker = true)
as
select
  a.id,
  a.id as id_almacen,
  a.id_sucursal,
  a.id_producto,
  a.stock,
  a.stock_minimo,
  coalesce(p.nombre, 'Producto') as nombre
from public.almacenes a
left join public.productos p on p.id = a.id_producto;

create table if not exists public.crm_whatsapp_config (
  id bigint generated by default as identity primary key,
  id_empresa integer not null references public.empresa(id) on delete cascade,
  proveedor text not null default 'meta_cloud'
    check (proveedor in ('meta_cloud', 'twilio', 'manual')),
  estado text not null default 'pendiente'
    check (estado in ('pendiente', 'conectado', 'pausado', 'error')),
  phone_number_id text,
  business_account_id text,
  display_phone text,
  default_country_code text not null default '1',
  default_language text not null default 'es',
  templates jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  updated_by integer references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_empresa)
);

create table if not exists public.crm_whatsapp_plantillas (
  id bigint generated by default as identity primary key,
  id_empresa integer not null references public.empresa(id) on delete cascade,
  tipo text not null
    check (tipo in ('bienvenida', 'cobro', 'factura', 'suscripcion_por_vencer')),
  nombre text not null,
  meta_template_name text,
  idioma text not null default 'es',
  cuerpo text not null,
  variables jsonb not null default '[]'::jsonb,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_empresa, tipo)
);

create table if not exists public.crm_whatsapp_mensajes (
  id bigint generated by default as identity primary key,
  id_empresa integer not null references public.empresa(id) on delete cascade,
  id_cliente_crm bigint references public.clientes_crm(id) on delete set null,
  id_pago bigint references public.crm_pagos(id) on delete set null,
  id_suscripcion bigint references public.crm_suscripciones(id) on delete set null,
  tipo text not null
    check (tipo in ('bienvenida', 'cobro', 'factura', 'suscripcion_por_vencer', 'manual')),
  canal text not null default 'whatsapp' check (canal = 'whatsapp'),
  destino text not null,
  plantilla text,
  cuerpo text not null,
  variables jsonb not null default '{}'::jsonb,
  estado text not null default 'borrador'
    check (estado in ('borrador', 'pendiente', 'enviado', 'error', 'cancelado')),
  provider_message_id text,
  scheduled_at timestamptz not null default now(),
  sent_at timestamptz,
  error text,
  created_by integer references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists crm_whatsapp_mensajes_empresa_estado_idx
  on public.crm_whatsapp_mensajes (id_empresa, estado, scheduled_at desc);

create table if not exists public.crm_automatizaciones (
  id bigint generated by default as identity primary key,
  id_empresa integer not null references public.empresa(id) on delete cascade,
  evento text not null
    check (evento in ('cliente_creado', 'pago_vencido', 'factura_emitida', 'suscripcion_por_vencer')),
  canal text not null default 'whatsapp' check (canal in ('whatsapp', 'email')),
  tipo_mensaje text not null
    check (tipo_mensaje in ('bienvenida', 'cobro', 'factura', 'suscripcion_por_vencer')),
  dias_antes integer not null default 0,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_empresa, evento, canal)
);

drop trigger if exists trg_crm_whatsapp_config_updated_at on public.crm_whatsapp_config;
create trigger trg_crm_whatsapp_config_updated_at
before update on public.crm_whatsapp_config
for each row execute function private.set_updated_at();

drop trigger if exists trg_crm_whatsapp_plantillas_updated_at on public.crm_whatsapp_plantillas;
create trigger trg_crm_whatsapp_plantillas_updated_at
before update on public.crm_whatsapp_plantillas
for each row execute function private.set_updated_at();

drop trigger if exists trg_crm_whatsapp_mensajes_updated_at on public.crm_whatsapp_mensajes;
create trigger trg_crm_whatsapp_mensajes_updated_at
before update on public.crm_whatsapp_mensajes
for each row execute function private.set_updated_at();

drop trigger if exists trg_crm_automatizaciones_updated_at on public.crm_automatizaciones;
create trigger trg_crm_automatizaciones_updated_at
before update on public.crm_automatizaciones
for each row execute function private.set_updated_at();

alter table public.crm_whatsapp_config enable row level security;
alter table public.crm_whatsapp_plantillas enable row level security;
alter table public.crm_whatsapp_mensajes enable row level security;
alter table public.crm_automatizaciones enable row level security;

-- Drop older FOR ALL policies that trigger permissive-policy advisor warnings,
-- then create explicit policies by action.
drop policy if exists "crm_planes_admin_write" on public.crm_planes;
drop policy if exists "crm_horarios_admin_write" on public.crm_horarios;
drop policy if exists "crm_suscripciones_staff_write" on public.crm_suscripciones;
drop policy if exists "crm_pagos_staff_write" on public.crm_pagos;
drop policy if exists "crm_asistencias_staff_write" on public.crm_asistencias;
drop policy if exists "cargos_admin_write" on public.cargos;
drop policy if exists "trabajadores_admin_write" on public.trabajadores;
drop policy if exists "empresa_modulos_admin_write" on public.empresa_modulos;
drop policy if exists "rol_modulos_admin_write" on public.rol_modulos;
drop policy if exists "parametros_sistema_admin_write" on public.parametros_sistema;
drop policy if exists "clientes_proveedores_company_write" on public.clientes_proveedores;
drop policy if exists "permisos_admin_write" on public.permisos;
drop policy if exists "permisos_default_admin_write" on public.permisos_dafault;

drop policy if exists "crm_planes_admin_insert" on public.crm_planes;
drop policy if exists "crm_planes_admin_update" on public.crm_planes;
drop policy if exists "crm_planes_admin_delete" on public.crm_planes;
drop policy if exists "crm_horarios_admin_insert" on public.crm_horarios;
drop policy if exists "crm_horarios_admin_update" on public.crm_horarios;
drop policy if exists "crm_horarios_admin_delete" on public.crm_horarios;
drop policy if exists "crm_suscripciones_staff_insert" on public.crm_suscripciones;
drop policy if exists "crm_suscripciones_staff_update" on public.crm_suscripciones;
drop policy if exists "crm_suscripciones_staff_delete" on public.crm_suscripciones;
drop policy if exists "crm_pagos_staff_insert" on public.crm_pagos;
drop policy if exists "crm_pagos_staff_update" on public.crm_pagos;
drop policy if exists "crm_pagos_staff_delete" on public.crm_pagos;
drop policy if exists "crm_asistencias_staff_insert" on public.crm_asistencias;
drop policy if exists "crm_asistencias_staff_update" on public.crm_asistencias;
drop policy if exists "crm_asistencias_staff_delete" on public.crm_asistencias;
drop policy if exists "cargos_admin_insert" on public.cargos;
drop policy if exists "cargos_admin_update" on public.cargos;
drop policy if exists "cargos_admin_delete" on public.cargos;
drop policy if exists "trabajadores_admin_insert" on public.trabajadores;
drop policy if exists "trabajadores_admin_update" on public.trabajadores;
drop policy if exists "trabajadores_admin_delete" on public.trabajadores;
drop policy if exists "empresa_modulos_admin_insert" on public.empresa_modulos;
drop policy if exists "empresa_modulos_admin_update" on public.empresa_modulos;
drop policy if exists "empresa_modulos_admin_delete" on public.empresa_modulos;
drop policy if exists "rol_modulos_admin_insert" on public.rol_modulos;
drop policy if exists "rol_modulos_admin_update" on public.rol_modulos;
drop policy if exists "rol_modulos_admin_delete" on public.rol_modulos;
drop policy if exists "parametros_sistema_admin_insert" on public.parametros_sistema;
drop policy if exists "parametros_sistema_admin_update" on public.parametros_sistema;
drop policy if exists "parametros_sistema_admin_delete" on public.parametros_sistema;
drop policy if exists "clientes_proveedores_company_insert" on public.clientes_proveedores;
drop policy if exists "clientes_proveedores_company_update" on public.clientes_proveedores;
drop policy if exists "clientes_proveedores_company_delete" on public.clientes_proveedores;
drop policy if exists "permisos_admin_insert" on public.permisos;
drop policy if exists "permisos_admin_update" on public.permisos;
drop policy if exists "permisos_admin_delete" on public.permisos;
drop policy if exists "permisos_default_admin_insert" on public.permisos_dafault;
drop policy if exists "permisos_default_admin_update" on public.permisos_dafault;
drop policy if exists "permisos_default_admin_delete" on public.permisos_dafault;

create policy "crm_planes_admin_insert" on public.crm_planes
for insert to authenticated
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));
create policy "crm_planes_admin_update" on public.crm_planes
for update to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));
create policy "crm_planes_admin_delete" on public.crm_planes
for delete to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

create policy "crm_horarios_admin_insert" on public.crm_horarios
for insert to authenticated
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));
create policy "crm_horarios_admin_update" on public.crm_horarios
for update to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));
create policy "crm_horarios_admin_delete" on public.crm_horarios
for delete to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

create policy "crm_suscripciones_staff_insert" on public.crm_suscripciones
for insert to authenticated
with check (id_empresa = (select private.current_empresa_id()));
create policy "crm_suscripciones_staff_update" on public.crm_suscripciones
for update to authenticated
using (id_empresa = (select private.current_empresa_id()))
with check (id_empresa = (select private.current_empresa_id()));
create policy "crm_suscripciones_staff_delete" on public.crm_suscripciones
for delete to authenticated
using (id_empresa = (select private.current_empresa_id()));

create policy "crm_pagos_staff_insert" on public.crm_pagos
for insert to authenticated
with check (id_empresa = (select private.current_empresa_id()));
create policy "crm_pagos_staff_update" on public.crm_pagos
for update to authenticated
using (id_empresa = (select private.current_empresa_id()))
with check (id_empresa = (select private.current_empresa_id()));
create policy "crm_pagos_staff_delete" on public.crm_pagos
for delete to authenticated
using (id_empresa = (select private.current_empresa_id()));

create policy "crm_asistencias_staff_insert" on public.crm_asistencias
for insert to authenticated
with check (id_empresa = (select private.current_empresa_id()));
create policy "crm_asistencias_staff_update" on public.crm_asistencias
for update to authenticated
using (id_empresa = (select private.current_empresa_id()))
with check (id_empresa = (select private.current_empresa_id()));
create policy "crm_asistencias_staff_delete" on public.crm_asistencias
for delete to authenticated
using (id_empresa = (select private.current_empresa_id()));

create policy "cargos_admin_insert" on public.cargos
for insert to authenticated
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));
create policy "cargos_admin_update" on public.cargos
for update to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));
create policy "cargos_admin_delete" on public.cargos
for delete to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

create policy "trabajadores_admin_insert" on public.trabajadores
for insert to authenticated
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));
create policy "trabajadores_admin_update" on public.trabajadores
for update to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));
create policy "trabajadores_admin_delete" on public.trabajadores
for delete to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

create policy "empresa_modulos_admin_insert" on public.empresa_modulos
for insert to authenticated
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));
create policy "empresa_modulos_admin_update" on public.empresa_modulos
for update to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));
create policy "empresa_modulos_admin_delete" on public.empresa_modulos
for delete to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

create policy "rol_modulos_admin_insert" on public.rol_modulos
for insert to authenticated
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));
create policy "rol_modulos_admin_update" on public.rol_modulos
for update to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));
create policy "rol_modulos_admin_delete" on public.rol_modulos
for delete to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

create policy "parametros_sistema_admin_insert" on public.parametros_sistema
for insert to authenticated
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));
create policy "parametros_sistema_admin_update" on public.parametros_sistema
for update to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));
create policy "parametros_sistema_admin_delete" on public.parametros_sistema
for delete to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

create policy "clientes_proveedores_company_insert" on public.clientes_proveedores
for insert to authenticated
with check (id_empresa = (select private.current_empresa_id()));
create policy "clientes_proveedores_company_update" on public.clientes_proveedores
for update to authenticated
using (id_empresa = (select private.current_empresa_id()))
with check (id_empresa = (select private.current_empresa_id()));
create policy "clientes_proveedores_company_delete" on public.clientes_proveedores
for delete to authenticated
using (id_empresa = (select private.current_empresa_id()));

create policy "permisos_admin_insert" on public.permisos
for insert to authenticated
with check (
  exists (
    select 1
    from public.usuarios u
    where u.id = permisos.id_usuario
      and u.id_empresa = (select private.current_empresa_id())
      and (select private.is_empresa_admin())
  )
);
create policy "permisos_admin_update" on public.permisos
for update to authenticated
using (
  exists (
    select 1
    from public.usuarios u
    where u.id = permisos.id_usuario
      and u.id_empresa = (select private.current_empresa_id())
      and (select private.is_empresa_admin())
  )
)
with check (
  exists (
    select 1
    from public.usuarios u
    where u.id = permisos.id_usuario
      and u.id_empresa = (select private.current_empresa_id())
      and (select private.is_empresa_admin())
  )
);
create policy "permisos_admin_delete" on public.permisos
for delete to authenticated
using (
  exists (
    select 1
    from public.usuarios u
    where u.id = permisos.id_usuario
      and u.id_empresa = (select private.current_empresa_id())
      and (select private.is_empresa_admin())
  )
);

create policy "permisos_default_admin_insert" on public.permisos_dafault
for insert to authenticated
with check ((select private.is_empresa_admin()));
create policy "permisos_default_admin_update" on public.permisos_dafault
for update to authenticated
using ((select private.is_empresa_admin()))
with check ((select private.is_empresa_admin()));
create policy "permisos_default_admin_delete" on public.permisos_dafault
for delete to authenticated
using ((select private.is_empresa_admin()));

drop policy if exists "crm_whatsapp_config_company_select" on public.crm_whatsapp_config;
create policy "crm_whatsapp_config_company_select"
on public.crm_whatsapp_config for select
to authenticated
using (id_empresa = (select private.current_empresa_id()));

drop policy if exists "crm_whatsapp_config_admin_insert" on public.crm_whatsapp_config;
create policy "crm_whatsapp_config_admin_insert"
on public.crm_whatsapp_config for insert
to authenticated
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "crm_whatsapp_config_admin_update" on public.crm_whatsapp_config;
create policy "crm_whatsapp_config_admin_update"
on public.crm_whatsapp_config for update
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "crm_whatsapp_config_admin_delete" on public.crm_whatsapp_config;
create policy "crm_whatsapp_config_admin_delete"
on public.crm_whatsapp_config for delete
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "crm_whatsapp_plantillas_company_select" on public.crm_whatsapp_plantillas;
create policy "crm_whatsapp_plantillas_company_select"
on public.crm_whatsapp_plantillas for select
to authenticated
using (id_empresa = (select private.current_empresa_id()));

drop policy if exists "crm_whatsapp_plantillas_admin_insert" on public.crm_whatsapp_plantillas;
create policy "crm_whatsapp_plantillas_admin_insert"
on public.crm_whatsapp_plantillas for insert
to authenticated
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "crm_whatsapp_plantillas_admin_update" on public.crm_whatsapp_plantillas;
create policy "crm_whatsapp_plantillas_admin_update"
on public.crm_whatsapp_plantillas for update
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "crm_whatsapp_plantillas_admin_delete" on public.crm_whatsapp_plantillas;
create policy "crm_whatsapp_plantillas_admin_delete"
on public.crm_whatsapp_plantillas for delete
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "crm_whatsapp_mensajes_company_select" on public.crm_whatsapp_mensajes;
create policy "crm_whatsapp_mensajes_company_select"
on public.crm_whatsapp_mensajes for select
to authenticated
using (id_empresa = (select private.current_empresa_id()));

drop policy if exists "crm_whatsapp_mensajes_staff_insert" on public.crm_whatsapp_mensajes;
create policy "crm_whatsapp_mensajes_staff_insert"
on public.crm_whatsapp_mensajes for insert
to authenticated
with check (id_empresa = (select private.current_empresa_id()));

drop policy if exists "crm_whatsapp_mensajes_staff_update" on public.crm_whatsapp_mensajes;
create policy "crm_whatsapp_mensajes_staff_update"
on public.crm_whatsapp_mensajes for update
to authenticated
using (id_empresa = (select private.current_empresa_id()))
with check (id_empresa = (select private.current_empresa_id()));

drop policy if exists "crm_whatsapp_mensajes_admin_delete" on public.crm_whatsapp_mensajes;
create policy "crm_whatsapp_mensajes_admin_delete"
on public.crm_whatsapp_mensajes for delete
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "crm_automatizaciones_company_select" on public.crm_automatizaciones;
create policy "crm_automatizaciones_company_select"
on public.crm_automatizaciones for select
to authenticated
using (id_empresa = (select private.current_empresa_id()));

drop policy if exists "crm_automatizaciones_admin_insert" on public.crm_automatizaciones;
create policy "crm_automatizaciones_admin_insert"
on public.crm_automatizaciones for insert
to authenticated
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "crm_automatizaciones_admin_update" on public.crm_automatizaciones;
create policy "crm_automatizaciones_admin_update"
on public.crm_automatizaciones for update
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "crm_automatizaciones_admin_delete" on public.crm_automatizaciones;
create policy "crm_automatizaciones_admin_delete"
on public.crm_automatizaciones for delete
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

-- Explicit Data API GRANTs for all browser-facing CRM/config/POS compatibility objects.
grant select on public.almacen, public.stock to authenticated;

grant select, insert, update, delete on
  public.crm_planes,
  public.crm_horarios,
  public.clientes_crm,
  public.crm_invitaciones,
  public.crm_suscripciones,
  public.crm_pagos,
  public.crm_asistencias,
  public.cargos,
  public.trabajadores,
  public.empresa_modulos,
  public.rol_modulos,
  public.parametros_sistema,
  public.crm_whatsapp_config,
  public.crm_whatsapp_plantillas,
  public.crm_whatsapp_mensajes,
  public.crm_automatizaciones
to authenticated;

grant select, insert, update, delete on
  public.clientes_proveedores,
  public.permisos,
  public.permisos_dafault
to authenticated;

grant select on public.modulos, public.crm_resumen_clientes to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on
  public.crm_planes,
  public.crm_horarios,
  public.clientes_crm,
  public.crm_invitaciones,
  public.crm_suscripciones,
  public.crm_pagos,
  public.crm_asistencias,
  public.cargos,
  public.trabajadores,
  public.empresa_modulos,
  public.rol_modulos,
  public.parametros_sistema,
  public.crm_whatsapp_config,
  public.crm_whatsapp_plantillas,
  public.crm_whatsapp_mensajes,
  public.crm_automatizaciones,
  public.almacen,
  public.stock,
  public.crm_resumen_clientes
from anon;

insert into public.modulos (nombre, descripcion, icono, link, etiquetas, "check")
select *
from (
  values
    ('WhatsApp CRM', 'Mensajes de cobro, bienvenida, facturas y vencimientos', 'logos:whatsapp-icon', '/crm/whatsapp', '#crm', true)
) as nuevos(nombre, descripcion, icono, link, etiquetas, "check")
where not exists (select 1 from public.modulos m where m.link = nuevos.link);

insert into public.crm_whatsapp_config (id_empresa, proveedor, estado, default_language)
select e.id, 'meta_cloud', 'pendiente', 'es'
from public.empresa e
where not exists (
  select 1 from public.crm_whatsapp_config c where c.id_empresa = e.id
);

insert into public.crm_whatsapp_plantillas (id_empresa, tipo, nombre, meta_template_name, cuerpo, variables)
select e.id, item.tipo, item.nombre, item.meta_template_name, item.cuerpo, item.variables::jsonb
from public.empresa e
cross join (
  values
    ('bienvenida', 'Bienvenida nuevo cliente', 'asc_bienvenida_cliente', 'Hola {{nombre}}, bienvenido a {{empresa}}. Tu registro ya esta activo. Gracias por confiar en nosotros.', '["nombre","empresa"]'),
    ('cobro', 'Nota de cobro', 'asc_nota_cobro', 'Hola {{nombre}}, tienes un pago pendiente de {{monto}} con vencimiento {{fecha_vencimiento}}. Puedes responder este mensaje para coordinar.', '["nombre","monto","fecha_vencimiento"]'),
    ('factura', 'Factura electronica', 'asc_factura_electronica', 'Hola {{nombre}}, tu factura {{referencia}} por {{monto}} ya esta lista. Gracias por tu pago.', '["nombre","referencia","monto"]'),
    ('suscripcion_por_vencer', 'Suscripcion por vencer', 'asc_suscripcion_por_vencer', 'Hola {{nombre}}, tu suscripcion finaliza el {{fecha_fin}}. Te quedan {{dias_restantes}} dia(s).', '["nombre","fecha_fin","dias_restantes"]')
) as item(tipo, nombre, meta_template_name, cuerpo, variables)
where not exists (
  select 1
  from public.crm_whatsapp_plantillas p
  where p.id_empresa = e.id and p.tipo = item.tipo
);

insert into public.crm_automatizaciones (id_empresa, evento, canal, tipo_mensaje, dias_antes, activo)
select e.id, item.evento, 'whatsapp', item.tipo_mensaje, item.dias_antes, true
from public.empresa e
cross join (
  values
    ('cliente_creado', 'bienvenida', 0),
    ('pago_vencido', 'cobro', 0),
    ('factura_emitida', 'factura', 0),
    ('suscripcion_por_vencer', 'suscripcion_por_vencer', 7)
) as item(evento, tipo_mensaje, dias_antes)
where not exists (
  select 1
  from public.crm_automatizaciones a
  where a.id_empresa = e.id and a.evento = item.evento and a.canal = 'whatsapp'
);
