
CREATE TABLE public.empresa (
    id bigint NOT NULL,
    nombre text DEFAULT 'Generica'::text NOT NULL,
    id_fiscal text DEFAULT '-'::text,
    direccion_fiscal text DEFAULT '-'::text,
    simbolo_moneda text DEFAULT '$'::text,
    logo text DEFAULT '-'::text,
    id_auth text DEFAULT ''::text NOT NULL,
    id_usuario bigint
);


ALTER TABLE public.empresa OWNER TO postgres;

--
-- TOC entry 302 (class 1259 OID 31005)
-- Name: almacenes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.almacenes (
    id bigint NOT NULL,
    id_sucursal bigint NOT NULL,
    id_producto bigint NOT NULL,
    stock numeric DEFAULT '0'::numeric,
    stock_minimo numeric DEFAULT '0'::numeric
);


ALTER TABLE public.almacenes OWNER TO postgres;

--
-- TOC entry 303 (class 1259 OID 31008)
-- Name: almacenes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.almacenes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.almacenes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 296 (class 1259 OID 29812)
-- Name: asignacion_sucursal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asignacion_sucursal (
    id bigint NOT NULL,
    id_sucursal bigint NOT NULL,
    id_usuario bigint
);


ALTER TABLE public.asignacion_sucursal OWNER TO postgres;

--
-- TOC entry 297 (class 1259 OID 29815)
-- Name: asignacion_sucursal_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.asignacion_sucursal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asignacion_sucursal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 292 (class 1259 OID 28772)
-- Name: categorias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categorias (
    id bigint NOT NULL,
    nombre text NOT NULL,
    color text,
    icono text DEFAULT '-'::text,
    id_empresa bigint
);


ALTER TABLE public.categorias OWNER TO postgres;

--
-- TOC entry 293 (class 1259 OID 28775)
-- Name: categorias_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categorias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 308 (class 1259 OID 31757)
-- Name: clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clientes (
    id bigint NOT NULL,
    nombres text NOT NULL,
    id_empresa bigint
);


ALTER TABLE public.clientes OWNER TO postgres;

--
-- TOC entry 309 (class 1259 OID 31760)
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 310 (class 1259 OID 31773)
-- Name: detalle_venta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalle_venta (
    id bigint NOT NULL,
    id_venta bigint NOT NULL,
    cantidad numeric DEFAULT '1'::numeric,
    precio_venta numeric,
    total numeric,
    descripcion text,
    id_producto bigint,
    precio_compra numeric,
    id_sucursal bigint,
    estado text DEFAULT 'nueva'::text
);


ALTER TABLE public.detalle_venta OWNER TO postgres;

--
-- TOC entry 311 (class 1259 OID 31776)
-- Name: detalle_venta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalle_venta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_venta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 295 (class 1259 OID 29792)
-- Name: empresa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.empresa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empresa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 312 (class 1259 OID 31840)
-- Name: kardex; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kardex (
    id bigint NOT NULL,
    fecha date NOT NULL,
    motivo text,
    cantidad numeric,
    id_producto bigint,
    id_usuario bigint,
    tipo text,
    estado text,
    total numeric,
    costo numeric,
    habia numeric,
    hay numeric
);


ALTER TABLE public.kardex OWNER TO postgres;

--
-- TOC entry 313 (class 1259 OID 31843)
-- Name: kardex_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kardex ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kardex_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 298 (class 1259 OID 30191)
-- Name: modulos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.modulos (
    id bigint NOT NULL,
    nombre text NOT NULL,
    "check" boolean DEFAULT false,
    descripcion text,
    icono text,
    link text
);


ALTER TABLE public.modulos OWNER TO postgres;

--
-- TOC entry 299 (class 1259 OID 30194)
-- Name: modulos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.modulos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modulos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 304 (class 1259 OID 31031)
-- Name: multiprecios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.multiprecios (
    id bigint NOT NULL,
    precio_venta numeric NOT NULL,
    id_producto bigint,
    cantidad numeric
);


ALTER TABLE public.multiprecios OWNER TO postgres;

--
-- TOC entry 305 (class 1259 OID 31034)
-- Name: multiprecios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.multiprecios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.multiprecios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 300 (class 1259 OID 30984)
-- Name: productos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.productos (
    id bigint NOT NULL,
    nombre text NOT NULL,
    precio_venta numeric DEFAULT '0'::numeric,
    precio_compra numeric DEFAULT '0'::numeric,
    id_categoria bigint,
    codigo_barras text,
    codigo_interno text,
    id_empresa bigint,
    sevende_por text,
    maneja_inventarios boolean,
    maneja_multiprecios boolean
);


ALTER TABLE public.productos OWNER TO postgres;

--
-- TOC entry 301 (class 1259 OID 30987)
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 290 (class 1259 OID 28673)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    nombre text NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 291 (class 1259 OID 28676)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 288 (class 1259 OID 28652)
-- Name: sucursales; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sucursales (
    id bigint NOT NULL,
    nombre text,
    direccion_fiscal text,
    id_empresa bigint,
    simbolo_moneda text
);


ALTER TABLE public.sucursales OWNER TO postgres;

--
-- TOC entry 289 (class 1259 OID 28655)
-- Name: sucursales_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sucursales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sucursales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 286 (class 1259 OID 28604)
-- Name: tipodocumento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipodocumento (
    id bigint NOT NULL,
    nombre text DEFAULT ''::text NOT NULL,
    id_empresa bigint
);


ALTER TABLE public.tipodocumento OWNER TO postgres;

--
-- TOC entry 287 (class 1259 OID 28607)
-- Name: tipodocumento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipodocumento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipodocumento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 284 (class 1259 OID 28592)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    nombres text DEFAULT '-'::text NOT NULL,
    id_tipodocumento bigint,
    nro_doc text DEFAULT '-'::text,
    telefono text DEFAULT '-'::text,
    id_rol bigint,
    correo text DEFAULT ''::text,
    fecharegistro date,
    direccion text DEFAULT '-'::text,
    estado text DEFAULT 'ACTIVO'::text,
    id_auth text
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 285 (class 1259 OID 28595)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 306 (class 1259 OID 31736)
-- Name: ventas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ventas (
    id bigint NOT NULL,
    fecha date DEFAULT now() NOT NULL,
    monto_total numeric DEFAULT '0'::numeric,
    tipo_de_pago text DEFAULT '-'::text,
    estado text DEFAULT 'nueva'::text,
    total_impuestos numeric DEFAULT '0'::numeric,
    id_usuario bigint,
    saldo numeric DEFAULT '0'::numeric,
    pago_con numeric DEFAULT '0'::numeric,
    referencia_tarjeta text DEFAULT '-'::text,
    vuelto numeric DEFAULT '0'::numeric,
    efectivo numeric DEFAULT '0'::numeric,
    credito numeric DEFAULT '0'::numeric,
    tarjeta numeric DEFAULT '0'::numeric,
    cantidad_productos bigint DEFAULT '0'::bigint,
    sub_total numeric DEFAULT '0'::numeric,
    id_cliente bigint,
    id_sucursal bigint,
    id_empresa bigint
);


ALTER TABLE public.ventas OWNER TO postgres;

--
-- TOC entry 307 (class 1259 OID 31739)
-- Name: ventas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ventas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.almacenes
    ADD CONSTRAINT almacenes_pkey PRIMARY KEY (id);


--
-- TOC entry 3732 (class 2606 OID 29820)
-- Name: asignacion_sucursal asignacion_sucursal_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asignacion_sucursal
    ADD CONSTRAINT asignacion_sucursal_pkey PRIMARY KEY (id);


--
-- TOC entry 3726 (class 2606 OID 28782)
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (id);


--
-- TOC entry 3744 (class 2606 OID 31767)
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- TOC entry 3746 (class 2606 OID 31783)
-- Name: detalle_venta detalle_venta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT detalle_venta_pkey PRIMARY KEY (id);


--
-- TOC entry 3728 (class 2606 OID 29811)
-- Name: empresa empresa_id_auth_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_id_auth_key UNIQUE (id_auth);


--
-- TOC entry 3730 (class 2606 OID 29799)
-- Name: empresa empresa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_pkey PRIMARY KEY (id);


--
-- TOC entry 3748 (class 2606 OID 31850)
-- Name: kardex kardex_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kardex
    ADD CONSTRAINT kardex_pkey PRIMARY KEY (id);


--
-- TOC entry 3734 (class 2606 OID 30202)
-- Name: modulos modulos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.modulos
    ADD CONSTRAINT modulos_pkey PRIMARY KEY (id);


--
-- TOC entry 3740 (class 2606 OID 31041)
-- Name: multiprecios multiprecios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multiprecios
    ADD CONSTRAINT multiprecios_pkey PRIMARY KEY (id);


--
-- TOC entry 3736 (class 2606 OID 30994)
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- TOC entry 3724 (class 2606 OID 28683)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 3722 (class 2606 OID 28662)
-- Name: sucursales sucursales_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sucursales
    ADD CONSTRAINT sucursales_pkey PRIMARY KEY (id);


--
-- TOC entry 3720 (class 2606 OID 28615)
-- Name: tipodocumento tipodocumento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipodocumento
    ADD CONSTRAINT tipodocumento_pkey PRIMARY KEY (id);


--
-- TOC entry 3716 (class 2606 OID 29947)
-- Name: usuarios usuarios_id_auth_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_id_auth_key UNIQUE (id_auth);


--
-- TOC entry 3718 (class 2606 OID 28603)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 3742 (class 2606 OID 31746)
-- Name: ventas ventas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT ventas_pkey PRIMARY KEY (id);


--
-- TOC entry 3774 (class 2620 OID 32158)
-- Name: ventas asignarclientegenericotrigger; Type: TRIGGER; Schema: public; Owner: postgres
--




--
-- TOC entry 3754 (class 2606 OID 30172)
-- Name: asignacion_sucursal asignacion_sucursal_id_sucursal_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asignacion_sucursal
    ADD CONSTRAINT asignacion_sucursal_id_sucursal_fkey FOREIGN KEY (id_sucursal) REFERENCES public.sucursales(id) ON DELETE CASCADE;


--
-- TOC entry 3755 (class 2606 OID 30177)
-- Name: asignacion_sucursal asignacion_sucursal_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asignacion_sucursal
    ADD CONSTRAINT asignacion_sucursal_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- TOC entry 3753 (class 2606 OID 30182)
-- Name: empresa empresa_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- TOC entry 3760 (class 2606 OID 31042)
-- Name: multiprecios multiprecios_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multiprecios
    ADD CONSTRAINT multiprecios_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- TOC entry 3758 (class 2606 OID 31478)
-- Name: almacenes public_almacenes_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.almacenes
    ADD CONSTRAINT public_almacenes_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.productos(id) ON DELETE CASCADE;


--
-- TOC entry 3759 (class 2606 OID 31691)
-- Name: almacenes public_almacenes_id_sucursal_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.almacenes
    ADD CONSTRAINT public_almacenes_id_sucursal_fkey FOREIGN KEY (id_sucursal) REFERENCES public.sucursales(id) ON DELETE CASCADE;


--
-- TOC entry 3752 (class 2606 OID 31676)
-- Name: categorias public_categorias_id_empresa_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT public_categorias_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES public.empresa(id) ON DELETE CASCADE;


--
-- TOC entry 3765 (class 2606 OID 32293)
-- Name: clientes public_clientes_id_empresa_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT public_clientes_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES public.empresa(id) ON DELETE CASCADE;


--
-- TOC entry 3766 (class 2606 OID 31789)
-- Name: detalle_venta public_detalle_venta_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT public_detalle_venta_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- TOC entry 3767 (class 2606 OID 32024)
-- Name: detalle_venta public_detalle_venta_id_sucursal_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT public_detalle_venta_id_sucursal_fkey FOREIGN KEY (id_sucursal) REFERENCES public.sucursales(id);


--
-- TOC entry 3768 (class 2606 OID 32282)
-- Name: detalle_venta public_detalle_venta_id_venta_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT public_detalle_venta_id_venta_fkey FOREIGN KEY (id_venta) REFERENCES public.ventas(id) ON DELETE CASCADE;


--
-- TOC entry 3769 (class 2606 OID 32298)
-- Name: kardex public_kardex_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kardex
    ADD CONSTRAINT public_kardex_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.productos(id) ON DELETE CASCADE;


--
-- TOC entry 3770 (class 2606 OID 31856)
-- Name: kardex public_kardex_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kardex
    ADD CONSTRAINT public_kardex_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- TOC entry 3756 (class 2606 OID 31681)
-- Name: productos public_productos_id_categoria_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT public_productos_id_categoria_fkey FOREIGN KEY (id_categoria) REFERENCES public.categorias(id) ON DELETE CASCADE;


--
-- TOC entry 3757 (class 2606 OID 31686)
-- Name: productos public_productos_id_empresa_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT public_productos_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES public.empresa(id) ON DELETE CASCADE;


--
-- TOC entry 3761 (class 2606 OID 31768)
-- Name: ventas public_ventas_id_cliente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT public_ventas_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES public.clientes(id);


--
-- TOC entry 3762 (class 2606 OID 32586)
-- Name: ventas public_ventas_id_empresa_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT public_ventas_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES public.empresa(id);


--
-- TOC entry 3763 (class 2606 OID 32523)
-- Name: ventas public_ventas_id_sucursal_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT public_ventas_id_sucursal_fkey FOREIGN KEY (id_sucursal) REFERENCES public.sucursales(id) ON DELETE CASCADE;


--
-- TOC entry 3764 (class 2606 OID 31747)
-- Name: ventas public_ventas_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT public_ventas_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- TOC entry 3751 (class 2606 OID 29953)
-- Name: sucursales sucursales_id_empresa_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sucursales
    ADD CONSTRAINT sucursales_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES public.empresa(id) ON DELETE CASCADE;


--
-- TOC entry 3750 (class 2606 OID 29948)
-- Name: tipodocumento tipodocumento_id_empresa_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipodocumento
    ADD CONSTRAINT tipodocumento_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES public.empresa(id) ON DELETE CASCADE;


--
-- TOC entry 3749 (class 2606 OID 29965)
-- Name: usuarios usuarios_id_rol_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_id_rol_fkey FOREIGN KEY (id_rol) REFERENCES public.roles(id);

--crear funciones y triggers
CREATE FUNCTION public.asignarclientegenerico() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
declare _id_cliente int;
begin
 --seleccionamos el id del cliente generico
 select id into _id_cliente from clientes where id_empresa = new.id_empresa;
-- editamos el cliente generico
 update ventas
 set id_cliente = _id_cliente  where id_cliente is null and id_empresa=new.id_empresa;
 return new;
end
$$;



--
-- TOC entry 588 (class 1255 OID 31456)
-- Name: buscarproductos(integer, text); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.buscarproductos(_id_empresa integer, buscador text) RETURNS TABLE(id integer, nombre text, precio_venta numeric, precio_compra numeric, id_categoria integer, sevende_por text, codigo_barras text, codigo_interno text, id_empresa integer, maneja_inventarios boolean, maneja_multiprecios boolean, p_venta text, p_compra text, categoria text)
    LANGUAGE sql
    AS $$
select p.id,
 p.nombre,p.precio_venta,p.precio_compra,p.id_categoria,p.sevende_por,p.codigo_barras,p.codigo_interno,p.id_empresa,p.maneja_inventarios,p.maneja_multiprecios,concat(e.simbolo_moneda,' ', p.precio_venta) as p_venta,concat(e.simbolo_moneda,' ', p.precio_compra) as p_compra,c.nombre as categoria
  from productos as p inner join empresa as e on e.id=p.id_empresa
  inner join categorias as c on c.id=p.id_categoria
  where LOWER(p.nombre) LIKE '%'||LOWER(buscador)||'%' and p.id_empresa=_id_empresa ;
$$;



--
-- TOC entry 557 (class 1255 OID 32052)
-- Name: detalleventaaumentarstock(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.detalleventaaumentarstock() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
--declarando valores a insertar
declare _habia numeric;
declare _hay numeric;
declare _maneja_inventarios bool;
declare _stock numeric;
begin
--editamos el stock en almacenes
select maneja_inventarios into _maneja_inventarios from productos where id=old.id_producto;
select stock into _stock from almacenes where id_producto=old.id_producto and id_sucursal=old.id_sucursal;

 if _maneja_inventarios=true and old.estado='confirmada' then
  
   update almacenes
   set stock= stock + old.cantidad 
   where id_producto=old.id_producto and id_sucursal=old.id_sucursal;

    --asignar valores a las variables
   select stock  into _hay
   from almacenes where id_producto=old.id_producto and id_sucursal=old.id_sucursal;
   select _hay - old.cantidad into _habia
   from almacenes where id_producto=old.id_producto and id_sucursal=old.id_sucursal;

   --insertamos los datos a la tabla de kardex
   insert into kardex(fecha,motivo,cantidad,id_producto,tipo,estado,total,costo,habia,hay)
   values(now(),'Detalle venta eliminada id: ' || old.id,old.cantidad,old.id_producto,'e','activo',old.cantidad*old.precio_compra,old.precio_compra,_habia,_hay);
  
 end if;
 return old;
end
$$;




--
-- TOC entry 556 (class 1255 OID 31794)
-- Name: detalleventastock(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.detalleventastock() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
--declarando valores a insertar
declare _habia numeric;
declare _hay numeric;
declare _maneja_inventarios bool;
declare _stock numeric;
begin
if new.estado = 'confirmada' then

--editamos el stock en almacenes
select maneja_inventarios into _maneja_inventarios from productos where id=new.id_producto;
select stock into _stock from almacenes where id_producto=new.id_producto and id_sucursal=new.id_sucursal;

 if _maneja_inventarios=true then
  if _stock>=new.cantidad then
   update almacenes
   set stock= stock - new.cantidad 
   where id_producto=new.id_producto and id_sucursal=new.id_sucursal;

    --asignar valores a las variables
   select stock  into _hay
   from almacenes where id_producto=new.id_producto and id_sucursal=new.id_sucursal;
   select _hay - new.cantidad into _habia
   from almacenes where id_producto=new.id_producto and id_sucursal=new.id_sucursal;

   --insertamos los datos a la tabla de kardex
   insert into kardex(fecha,motivo,cantidad,id_producto,tipo,estado,total,costo,habia,hay)
   values(now(),'Venta id: ' || new.id_venta,new.cantidad,new.id_producto,'s','activo',new.cantidad*new.precio_compra,new.precio_compra,_habia,_hay);
  else
    raise exception 'El stock tiene que ser mayor o igual a la cantidad';
  end if;
 end if;
 return new;

end if;
end
$$;




--
-- TOC entry 584 (class 1255 OID 30852)
-- Name: editarcategorias(text, integer, text, integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.editarcategorias(_nombre text, _id_empresa integer, _color text, _id integer) RETURNS void
    LANGUAGE plpgsql
    AS $$
begin
 perform 1 from categorias where id != _id and nombre = _nombre and id_empresa=_id_empresa;
 if found then
  raise exception 'Datos duplicados';
 else
  update categorias
  set
  nombre=_nombre,
  color=_color
  where id = _id;
 end if;  
end;
$$;




--
-- TOC entry 586 (class 1255 OID 30921)
-- Name: editarmarca(text, integer, integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.editarmarca(_nombre text, _id_empresa integer, _id integer) RETURNS void
    LANGUAGE plpgsql
    AS $$
begin
 perform 1 from marca where nombre=_nombre and id_empresa=_id_empresa and id!=_id;
 if found then
   raise exception 'Datos duplicados';
 else
  update marca
  set nombre=_nombre
  where id=_id;
  end if;
end;
$$;




--
-- TOC entry 362 (class 1255 OID 31616)
-- Name: editarproductos(integer, text, numeric, numeric, integer, text, text, integer, text, boolean); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.editarproductos(_id integer, _nombre text, _precio_venta numeric, _precio_compra numeric, _id_categoria integer, _codigo_barras text, _codigo_interno text, _id_empresa integer, _sevende_por text, _maneja_inventarios boolean) RETURNS void
    LANGUAGE plpgsql
    AS $$
begin
 perform 1 from productos where nombre=_nombre and id_empresa=_id_empresa and id!=_id;
 if found then
   raise exception 'Nombre de producto duplicado';  
 else
    perform 1 from productos where (codigo_interno=_codigo_interno and id_empresa=_id_empresa and id!=_id) or 
    (codigo_barras=_codigo_barras
     and id_empresa=_id_empresa and id!=_id);
    if found then
     raise exception 'Codigo de barra ó interno duplicado';
    else
     update  productos set nombre=_nombre,precio_venta=_precio_venta,precio_compra=_precio_compra,id_categoria=_id_categoria,codigo_barras=_codigo_barras,codigo_interno=_codigo_interno,sevende_por=_sevende_por,maneja_inventarios=_maneja_inventarios
     where id=_id;
     end if;
  end if;
end;
$$;




--
-- TOC entry 581 (class 1255 OID 29723)
-- Name: insertarcategorias(text, text, text, integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.insertarcategorias(_nombre text, _color text, _icono text, _id_empresa integer) RETURNS integer
    LANGUAGE plpgsql
    AS $$
declare nuevo_id int;
begin
 perform 1 from categorias where nombre=_nombre and id_empresa=_id_empresa;
 if found then
   raise exception 'Datos duplicados';
 else
   insert into categorias(nombre,color,icono,id_empresa)
   values(_nombre,_color,_icono,_id_empresa)
   returning id into nuevo_id;
   return nuevo_id;
  end if;
end;
$$;




CREATE FUNCTION public.insertardetalleventa(_id_venta integer, _cantidad numeric, _precio_venta numeric, _total numeric, _descripcion text, _id_producto integer, _precio_compra numeric, _id_sucursal integer, _id_almacen integer) RETURNS void
    LANGUAGE plpgsql
    AS $$
declare nuevo_id int;
begin
 perform 1 from detalle_venta inner join productos as p on p.id=detalle_venta.id_producto
 where p.id=_id_producto  and id_venta=_id_venta and estado='nueva';
 if found then
 update detalle_venta
 set cantidad = cantidad+_cantidad,
 total=(cantidad+_cantidad)*precio_venta
 where id_producto=_id_producto and id_venta=_id_venta and estado='nueva';
 else
 insert into detalle_venta( id_venta, cantidad, precio_venta, total, descripcion, id_producto, precio_compra, id_sucursal, id_almacen
)
values( _id_venta, _cantidad, _precio_venta, _total, _descripcion, _id_producto, _precio_compra, _id_sucursal, _id_almacen
);
end if;

end;
$$;




--
-- TOC entry 585 (class 1255 OID 30899)
-- Name: insertarmarca(text, integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.insertarmarca(_nombre text, _id_empresa integer) RETURNS void
    LANGUAGE plpgsql
    AS $$
begin
 perform 1 from marca where nombre=_nombre and id_empresa=_id_empresa;
 if found then
   raise exception 'Datos duplicados';
 else
   insert into marca(nombre,id_empresa)
   values(_nombre,_id_empresa);
  end if;
end;
$$;




--
-- TOC entry 587 (class 1255 OID 31200)
-- Name: insertarproductos(text, numeric, numeric, integer, text, text, integer, text, boolean, boolean); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.insertarproductos(_nombre text, _precio_venta numeric, _precio_compra numeric, _id_categoria integer, _codigo_barras text, _codigo_interno text, _id_empresa integer, _sevende_por text, _maneja_inventarios boolean, _maneja_multiprecios boolean) RETURNS integer
    LANGUAGE plpgsql
    AS $$
declare nuevo_id int;
begin
 perform 1 from productos where nombre=_nombre and id_empresa=_id_empresa;
 if found then
   raise exception 'Nombre de producto duplicado';  
 else
    perform 1 from productos where codigo_interno=_codigo_interno or 
    codigo_barras=_codigo_barras
     and id_empresa=_id_empresa ;
    if found then
     raise exception 'Codigo de barra ó interno duplicado';
    else
     insert into productos(nombre,precio_venta,precio_compra,id_categoria,codigo_barras,codigo_interno,id_empresa,sevende_por,maneja_inventarios,maneja_multiprecios)
     values(_nombre,_precio_venta,_precio_compra,_id_categoria,_codigo_barras,_codigo_interno,_id_empresa,_sevende_por,_maneja_inventarios,_maneja_multiprecios)
     returning id into nuevo_id;
     return nuevo_id;
     end if;
  end if;
end;
$$;




--
-- TOC entry 580 (class 1255 OID 28695)
-- Name: insertpordefecto(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.insertpordefecto() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
declare new_id_sucursal int;
begin
 insert into tipodocumento(nombre,id_empresa)
 values('Generico',new.id);

 insert into sucursales(nombre,direccion_fiscal,id_empresa,simbolo_moneda)
 values(new.nombre,new.direccion_fiscal,new.id,new.simbolo_moneda)
 returning id into new_id_sucursal;

 insert into asignacion_sucursal(id_sucursal,id_usuario)
 values(new_id_sucursal,new.id_usuario);

 insert into categorias(nombre,color,icono,id_empresa)
 values('General','#FEC701','-',new.id);

 insert into clientes(nombres,id_empresa)
 values ('Generico',new.id);

 

 return new;
end
$$;




--
-- TOC entry 574 (class 1255 OID 33804)
-- Name: mostrardetalleventa(integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.mostrardetalleventa(_id_venta integer) RETURNS TABLE(producto text, precio_venta numeric, cantidad numeric, estado text, total numeric, id integer)
    LANGUAGE sql
    AS $$
select p.nombre as producto,dv.precio_venta,dv.cantidad,dv.estado,dv.total,dv.id from detalle_venta as dv
inner join productos as p on p.id=dv.id_producto
inner join sucursales as s on s.id=dv.id_sucursal

where dv.id_venta = _id_venta;
$$;




--
-- TOC entry 294 (class 1259 OID 29789)
-- Name: empresa; Type: TABLE; Schema: public; Owner: postgres
--





--
-- TOC entry 583 (class 1255 OID 30768)
-- Name: mostrarempresaxiduser(integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.mostrarempresaxiduser(_id_usuario integer) RETURNS TABLE(result public.empresa)
    LANGUAGE sql
    AS $$
select empresa.* from asignacion_sucursal inner join usuarios on usuarios.id=asignacion_sucursal.id_usuario inner join sucursales on sucursales.id=asignacion_sucursal.id_sucursal inner join empresa on empresa.id=sucursales.id_empresa
where asignacion_sucursal.id_usuario=_id_usuario;

$$;




--
-- TOC entry 589 (class 1255 OID 31434)
-- Name: mostrarproductos(integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.mostrarproductos(_id_empresa integer) RETURNS TABLE(id integer, nombre text, precio_venta numeric, precio_compra numeric, id_categoria integer, sevende_por text, codigo_barras text, codigo_interno text, id_empresa integer, maneja_inventarios boolean, maneja_multiprecios boolean, p_venta text, p_compra text, categoria text)
    LANGUAGE sql
    AS $$
select p.id,
 p.nombre,p.precio_venta,p.precio_compra,p.id_categoria,p.sevende_por,p.codigo_barras,p.codigo_interno,p.id_empresa,p.maneja_inventarios,p.maneja_multiprecios,concat(e.simbolo_moneda,' ', p.precio_venta) as p_venta,concat(e.simbolo_moneda,' ', p.precio_compra) as p_compra,c.nombre as categoria
  from productos as p inner join empresa as e on e.id=p.id_empresa
  inner join categorias as c on c.id=p.id_categoria
  where p.id_empresa=_id_empresa;
$$;




--
-- TOC entry 559 (class 1255 OID 32459)
-- Name: mostrarsucursalesasignadas(integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.mostrarsucursalesasignadas(_id_usuario integer) RETURNS TABLE(id_sucursal integer, sucursal text, id_usuario integer, id_asignacion_sucursal integer)
    LANGUAGE sql
    AS $$
select s.id as id_sucursal,  s.nombre as sucursal,a.id_usuario,a.id as id_asignacion_sucursal  from 
asignacion_sucursal as a inner join sucursales
 as s on s.id=a.id_sucursal
 where a.id_usuario = _id_usuario;
$$;




--
-- TOC entry 590 (class 1255 OID 31484)
-- Name: updateuseinventariosproductos(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.updateuseinventariosproductos() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
 update productos
 set maneja_inventarios=false
 where id=old.id_producto;
 return old;
end
$$;




--
-- TOC entry 582 (class 1255 OID 30028)
-- Name: updateuserempresa(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.updateuserempresa() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
 update empresa
 set id_usuario=new.id
 where id_usuario is null;

 update asignacion_sucursal
 set id_usuario= new.id
 where id_usuario is null;
 return new;
end
$$;



--triggers
CREATE TRIGGER asignarclientegenericotrigger AFTER INSERT ON public.ventas FOR EACH ROW EXECUTE FUNCTION public.asignarclientegenerico();


--
-- TOC entry 3775 (class 2620 OID 32074)
-- Name: detalle_venta detalleventaaumentarstocktrigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER detalleventaaumentarstocktrigger BEFORE DELETE ON public.detalle_venta FOR EACH ROW EXECUTE FUNCTION public.detalleventaaumentarstock();


--
-- TOC entry 3776 (class 2620 OID 31816)
-- Name: detalle_venta detalleventastocktrigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER detalleventastocktrigger AFTER UPDATE OF estado ON public.detalle_venta FOR EACH ROW EXECUTE FUNCTION public.detalleventastock();


--
-- TOC entry 3771 (class 2620 OID 30050)
-- Name: usuarios editaruserempresatrigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER editaruserempresatrigger AFTER INSERT ON public.usuarios FOR EACH ROW EXECUTE FUNCTION public.updateuserempresa();


--
-- TOC entry 3772 (class 2620 OID 29864)
-- Name: empresa pordefectotrigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER pordefectotrigger AFTER INSERT ON public.empresa FOR EACH ROW EXECUTE FUNCTION public.insertpordefecto();


--
-- TOC entry 3773 (class 2620 OID 31506)
-- Name: almacenes updateuseinventariosproductostrigger; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER updateuseinventariosproductostrigger AFTER DELETE ON public.almacenes FOR EACH ROW EXECUTE FUNCTION public.updateuseinventariosproductos();
--

--crear policys
CREATE POLICY "Enable delete for users based on user_id" ON public.categorias FOR DELETE TO authenticated USING ((id = id));


--
-- TOC entry 3944 (class 3256 OID 28811)
-- Name: categorias Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable insert for authenticated users only" ON public.categorias FOR INSERT TO authenticated WITH CHECK (true);


--
-- TOC entry 3943 (class 3256 OID 28810)
-- Name: categorias Enable read access for all users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable read access for all users" ON public.categorias FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3945 (class 3256 OID 28812)
-- Name: categorias Enable update for users based on email; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Enable update for users based on email" ON public.categorias FOR UPDATE TO authenticated USING ((id = id)) WITH CHECK ((id = id));
--

-- ActiveSelfControl CRM extension

create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
grant usage on schema private to authenticated;

alter table public.empresa
  add column if not exists iso text default 'US',
  add column if not exists pais text default 'United States',
  add column if not exists currency text default 'USD',
  add column if not exists impuesto text default 'IMP',
  add column if not exists valor_impuesto numeric default 0,
  add column if not exists nombre_moneda text default 'US Dollar',
  add column if not exists correo text default '',
  add column if not exists pie_pagina_ticket text default 'Gracias por su compra';

alter table public.usuarios
  add column if not exists tema text default 'dark',
  add column if not exists id_empresa bigint references public.empresa(id) on delete set null;

alter table public.modulos
  add column if not exists etiquetas text default '#default';

create table if not exists public.clientes_proveedores (
  id bigint generated by default as identity primary key,
  nombres text not null,
  id_empresa bigint references public.empresa(id) on delete cascade,
  direccion text default '',
  telefono text default '',
  email text,
  identificador_nacional text default '',
  identificador_fiscal text default '',
  tipo text not null default 'cliente',
  estado text default 'activo',
  fecha_registro date default current_date
);

do $$
begin
  if to_regclass('public.clientes') is not null then
    execute $sql$
      insert into public.clientes_proveedores (
        id,
        nombres,
        id_empresa,
        tipo,
        estado
      )
      select
        c.id,
        c.nombres,
        c.id_empresa,
        'cliente',
        'activo'
      from public.clientes c
      where not exists (
        select 1
        from public.clientes_proveedores cp
        where cp.id = c.id
      )
      on conflict (id) do nothing
    $sql$;
  end if;
end;
$$;

create table if not exists public.permisos (
  id bigint generated by default as identity primary key,
  id_usuario bigint not null references public.usuarios(id) on delete cascade,
  idmodulo bigint not null references public.modulos(id) on delete cascade,
  unique (id_usuario, idmodulo)
);

create table if not exists public.permisos_dafault (
  id bigint generated by default as identity primary key,
  id_rol bigint references public.roles(id) on delete cascade,
  idmodulo bigint references public.modulos(id) on delete cascade
);

do $$
begin
  if to_regclass('public.asignacion_sucursal') is not null then
    execute $sql$
      update public.usuarios u
      set id_empresa = resolved.id_empresa
      from (
        select distinct on (a.id_usuario)
          a.id_usuario,
          s.id_empresa
        from public.asignacion_sucursal a
        join public.sucursales s on s.id = a.id_sucursal
        where s.id_empresa is not null
        order by a.id_usuario, s.id_empresa
      ) resolved
      where u.id = resolved.id_usuario
        and u.id_empresa is null
    $sql$;
  end if;
end;
$$;

create or replace function private.sync_usuario_empresa_from_assignment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.id_usuario is not null then
    update public.usuarios u
    set id_empresa = s.id_empresa
    from public.sucursales s
    where s.id = new.id_sucursal
      and u.id = new.id_usuario
      and u.id_empresa is distinct from s.id_empresa;
  end if;

  return new;
end;
$$;

revoke all on function private.sync_usuario_empresa_from_assignment() from public, anon, authenticated;

do $$
begin
  if to_regclass('public.asignacion_sucursal') is not null then
    execute 'drop trigger if exists trg_asignacion_sucursal_sync_usuario_empresa on public.asignacion_sucursal';
    execute $sql$
      create trigger trg_asignacion_sucursal_sync_usuario_empresa
      after insert or update of id_sucursal, id_usuario on public.asignacion_sucursal
      for each row execute function private.sync_usuario_empresa_from_assignment()
    $sql$;
  end if;
end;
$$;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function private.current_usuario_id()
returns bigint
language sql
stable
security definer
set search_path = public, auth
as $$
  select u.id
  from public.usuarios u
  where u.id_auth::text = (select auth.uid()::text)
  limit 1;
$$;

create or replace function private.current_empresa_id()
returns bigint
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  empresa_id bigint;
begin
  select nullif(to_jsonb(u)->>'id_empresa', '')::bigint
  into empresa_id
  from public.usuarios u
  where u.id_auth::text = (select auth.uid()::text)
  limit 1;

  if empresa_id is not null then
    return empresa_id;
  end if;

  if to_regclass('public.asignacion_sucursal') is not null then
    execute $sql$
      select s.id_empresa
      from public.usuarios u
      join public.asignacion_sucursal a on a.id_usuario = u.id
      join public.sucursales s on s.id = a.id_sucursal
      where u.id_auth::text = auth.uid()::text
      limit 1
    $sql$
    into empresa_id;
  end if;

  return empresa_id;
end;
$$;

create or replace function private.is_empresa_admin()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.usuarios u
    join public.roles r on r.id = u.id_rol
    where u.id_auth::text = (select auth.uid()::text)
      and lower(r.nombre) in ('superadmin', 'administrador', 'admin')
  );
$$;

revoke all on function private.set_updated_at() from public, anon, authenticated;
revoke all on function private.current_usuario_id() from public, anon, authenticated;
revoke all on function private.current_empresa_id() from public, anon, authenticated;
revoke all on function private.is_empresa_admin() from public, anon, authenticated;
grant execute on function private.current_usuario_id() to authenticated;
grant execute on function private.current_empresa_id() to authenticated;
grant execute on function private.is_empresa_admin() to authenticated;

create table if not exists public.crm_planes (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  nombre text not null,
  descripcion text,
  precio numeric(12,2) not null default 0 check (precio >= 0),
  periodicidad text not null default 'mensual'
    check (periodicidad in ('diario', 'semanal', 'quincenal', 'mensual', 'trimestral', 'anual')),
  duracion_dias integer not null default 30 check (duracion_dias > 0),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_empresa, nombre)
);

create table if not exists public.crm_horarios (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  nombre text not null,
  hora_entrada time not null,
  hora_salida time not null,
  dias_semana smallint[] not null default '{1,2,3,4,5}',
  tolerancia_minutos integer not null default 10 check (tolerancia_minutos >= 0),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_empresa, nombre),
  check (hora_salida > hora_entrada)
);

create table if not exists public.clientes_crm (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  id_cliente_proveedor bigint references public.clientes_proveedores(id) on delete set null,
  id_auth uuid references auth.users(id) on delete set null,
  codigo text,
  nombres text not null,
  apellidos text,
  email text,
  telefono text,
  direccion text,
  identificador_nacional text,
  identificador_fiscal text,
  fecha_nacimiento date,
  estado text not null default 'prospecto'
    check (estado in ('prospecto', 'activo', 'inactivo', 'suspendido')),
  origen text not null default 'manual'
    check (origen in ('manual', 'invitacion', 'pos', 'importado')),
  notas text,
  creado_por bigint references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (email is null or email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

create unique index if not exists clientes_crm_empresa_email_uidx
  on public.clientes_crm (id_empresa, lower(email))
  where email is not null;

create unique index if not exists clientes_crm_empresa_codigo_uidx
  on public.clientes_crm (id_empresa, codigo)
  where codigo is not null;

create table if not exists public.crm_invitaciones (
  id uuid primary key default extensions.gen_random_uuid(),
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  email text not null,
  token_hash text not null,
  estado text not null default 'pendiente'
    check (estado in ('pendiente', 'aceptada', 'expirada', 'cancelada')),
  id_plan bigint references public.crm_planes(id) on delete set null,
  id_cliente_crm bigint references public.clientes_crm(id) on delete set null,
  invited_by bigint references public.usuarios(id) on delete set null,
  expires_at timestamptz not null default (now() + interval '7 days'),
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

create unique index if not exists crm_invitaciones_pendientes_email_uidx
  on public.crm_invitaciones (id_empresa, lower(email))
  where estado = 'pendiente';

create table if not exists public.crm_suscripciones (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  id_cliente_crm bigint not null references public.clientes_crm(id) on delete cascade,
  id_plan bigint not null references public.crm_planes(id) on delete restrict,
  fecha_inicio date not null default current_date,
  fecha_fin date not null,
  precio_pactado numeric(12,2) not null default 0 check (precio_pactado >= 0),
  auto_renovar boolean not null default false,
  estado text not null default 'activa'
    check (estado in ('activa', 'pausada', 'vencida', 'cancelada')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (fecha_fin >= fecha_inicio)
);

create table if not exists public.crm_pagos (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  id_cliente_crm bigint not null references public.clientes_crm(id) on delete cascade,
  id_suscripcion bigint references public.crm_suscripciones(id) on delete set null,
  id_venta bigint references public.ventas(id) on delete set null,
  monto numeric(12,2) not null check (monto >= 0),
  moneda text not null default 'USD',
  metodo_pago text,
  referencia text,
  fecha_pago timestamptz,
  fecha_vencimiento date,
  periodo_inicio date,
  periodo_fin date,
  estado text not null default 'pendiente'
    check (estado in ('pendiente', 'pagado', 'vencido', 'anulado')),
  registrado_por bigint references public.usuarios(id) on delete set null,
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.crm_asistencias (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  id_cliente_crm bigint not null references public.clientes_crm(id) on delete cascade,
  id_horario bigint references public.crm_horarios(id) on delete set null,
  fecha date not null default current_date,
  hora_entrada timestamptz,
  hora_salida timestamptz,
  estado text not null default 'presente'
    check (estado in ('presente', 'tarde', 'ausente', 'salida_registrada')),
  registrado_por bigint references public.usuarios(id) on delete set null,
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (hora_salida is null or hora_entrada is null or hora_salida >= hora_entrada)
);

create index if not exists crm_asistencias_cliente_fecha_idx
  on public.crm_asistencias (id_cliente_crm, fecha desc);

create table if not exists public.cargos (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  nombre text not null,
  descripcion text,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_empresa, nombre)
);

create table if not exists public.trabajadores (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  id_usuario bigint references public.usuarios(id) on delete set null,
  id_cargo bigint references public.cargos(id) on delete set null,
  id_horario bigint references public.crm_horarios(id) on delete set null,
  nombres text not null,
  email text,
  telefono text,
  fecha_ingreso date not null default current_date,
  salario numeric(12,2) check (salario is null or salario >= 0),
  estado text not null default 'activo'
    check (estado in ('activo', 'inactivo', 'suspendido')),
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (email is null or email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

create unique index if not exists trabajadores_empresa_email_uidx
  on public.trabajadores (id_empresa, lower(email))
  where email is not null;

create table if not exists public.empresa_modulos (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  idmodulo bigint not null references public.modulos(id) on delete cascade,
  habilitado boolean not null default true,
  updated_by bigint references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_empresa, idmodulo)
);

create table if not exists public.rol_modulos (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  id_rol bigint not null references public.roles(id) on delete cascade,
  idmodulo bigint not null references public.modulos(id) on delete cascade,
  puede_ver boolean not null default true,
  puede_crear boolean not null default false,
  puede_editar boolean not null default false,
  puede_eliminar boolean not null default false,
  updated_by bigint references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_empresa, id_rol, idmodulo)
);

create table if not exists public.parametros_sistema (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  clave text not null,
  valor jsonb not null default '{}'::jsonb,
  descripcion text,
  updated_by bigint references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_empresa, clave)
);

create or replace function private.crm_sync_cliente_pos()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  cliente_pos_id bigint;
begin
  if tg_op = 'INSERT' then
    if new.id_cliente_proveedor is null then
      insert into public.clientes_proveedores (
        nombres,
        id_empresa,
        direccion,
        telefono,
        email,
        identificador_nacional,
        identificador_fiscal,
        tipo,
        estado
      ) values (
        trim(concat_ws(' ', new.nombres, new.apellidos)),
        new.id_empresa,
        coalesce(new.direccion, ''),
        coalesce(new.telefono, ''),
        new.email,
        coalesce(new.identificador_nacional, ''),
        coalesce(new.identificador_fiscal, ''),
        'cliente',
        new.estado
      )
      returning id into cliente_pos_id;

      new.id_cliente_proveedor = cliente_pos_id;
    end if;
    return new;
  end if;

  if tg_op = 'UPDATE' and new.id_cliente_proveedor is not null then
    update public.clientes_proveedores
    set nombres = trim(concat_ws(' ', new.nombres, new.apellidos)),
        direccion = coalesce(new.direccion, ''),
        telefono = coalesce(new.telefono, ''),
        email = new.email,
        identificador_nacional = coalesce(new.identificador_nacional, ''),
        identificador_fiscal = coalesce(new.identificador_fiscal, ''),
        estado = new.estado
    where id = new.id_cliente_proveedor
      and id_empresa = new.id_empresa;
  end if;

  return new;
end;
$$;

revoke all on function private.crm_sync_cliente_pos() from public, anon, authenticated;

drop trigger if exists trg_crm_planes_updated_at on public.crm_planes;
create trigger trg_crm_planes_updated_at
before update on public.crm_planes
for each row execute function private.set_updated_at();

drop trigger if exists trg_crm_horarios_updated_at on public.crm_horarios;
create trigger trg_crm_horarios_updated_at
before update on public.crm_horarios
for each row execute function private.set_updated_at();

drop trigger if exists trg_clientes_crm_updated_at on public.clientes_crm;
create trigger trg_clientes_crm_updated_at
before update on public.clientes_crm
for each row execute function private.set_updated_at();

drop trigger if exists trg_clientes_crm_sync_pos_insert on public.clientes_crm;
create trigger trg_clientes_crm_sync_pos_insert
before insert on public.clientes_crm
for each row execute function private.crm_sync_cliente_pos();

drop trigger if exists trg_clientes_crm_sync_pos_update on public.clientes_crm;
create trigger trg_clientes_crm_sync_pos_update
after update of nombres, apellidos, direccion, telefono, email, identificador_nacional, identificador_fiscal, estado
on public.clientes_crm
for each row execute function private.crm_sync_cliente_pos();

drop trigger if exists trg_crm_invitaciones_updated_at on public.crm_invitaciones;
create trigger trg_crm_invitaciones_updated_at
before update on public.crm_invitaciones
for each row execute function private.set_updated_at();

drop trigger if exists trg_crm_suscripciones_updated_at on public.crm_suscripciones;
create trigger trg_crm_suscripciones_updated_at
before update on public.crm_suscripciones
for each row execute function private.set_updated_at();

drop trigger if exists trg_crm_pagos_updated_at on public.crm_pagos;
create trigger trg_crm_pagos_updated_at
before update on public.crm_pagos
for each row execute function private.set_updated_at();

drop trigger if exists trg_crm_asistencias_updated_at on public.crm_asistencias;
create trigger trg_crm_asistencias_updated_at
before update on public.crm_asistencias
for each row execute function private.set_updated_at();

drop trigger if exists trg_cargos_updated_at on public.cargos;
create trigger trg_cargos_updated_at
before update on public.cargos
for each row execute function private.set_updated_at();

drop trigger if exists trg_trabajadores_updated_at on public.trabajadores;
create trigger trg_trabajadores_updated_at
before update on public.trabajadores
for each row execute function private.set_updated_at();

drop trigger if exists trg_empresa_modulos_updated_at on public.empresa_modulos;
create trigger trg_empresa_modulos_updated_at
before update on public.empresa_modulos
for each row execute function private.set_updated_at();

drop trigger if exists trg_rol_modulos_updated_at on public.rol_modulos;
create trigger trg_rol_modulos_updated_at
before update on public.rol_modulos
for each row execute function private.set_updated_at();

drop trigger if exists trg_parametros_sistema_updated_at on public.parametros_sistema;
create trigger trg_parametros_sistema_updated_at
before update on public.parametros_sistema
for each row execute function private.set_updated_at();

alter table public.crm_planes enable row level security;
alter table public.crm_horarios enable row level security;
alter table public.clientes_crm enable row level security;
alter table public.crm_invitaciones enable row level security;
alter table public.crm_suscripciones enable row level security;
alter table public.crm_pagos enable row level security;
alter table public.crm_asistencias enable row level security;
alter table public.cargos enable row level security;
alter table public.trabajadores enable row level security;
alter table public.empresa_modulos enable row level security;
alter table public.rol_modulos enable row level security;
alter table public.parametros_sistema enable row level security;
alter table public.clientes_proveedores enable row level security;
alter table public.permisos enable row level security;
alter table public.permisos_dafault enable row level security;
alter table public.modulos enable row level security;

grant select, insert, update, delete on
  public.crm_planes,
  public.crm_horarios,
  public.clientes_crm,
  public.crm_invitaciones,
  public.crm_suscripciones,
  public.crm_pagos,
  public.crm_asistencias,
  public.cargos,
  public.trabajadores,
  public.empresa_modulos,
  public.rol_modulos,
  public.parametros_sistema
to authenticated;

grant select, insert, update, delete on
  public.clientes_proveedores,
  public.permisos,
  public.permisos_dafault
to authenticated;

grant select on public.modulos to authenticated;

grant usage, select on all sequences in schema public to authenticated;

revoke all on
  public.crm_planes,
  public.crm_horarios,
  public.clientes_crm,
  public.crm_invitaciones,
  public.crm_suscripciones,
  public.crm_pagos,
  public.crm_asistencias,
  public.cargos,
  public.trabajadores,
  public.empresa_modulos,
  public.rol_modulos,
  public.parametros_sistema
from anon;

revoke all on
  public.clientes_proveedores,
  public.permisos,
  public.permisos_dafault,
  public.modulos
from anon;

drop policy if exists "modulos_authenticated_select" on public.modulos;
create policy "modulos_authenticated_select"
on public.modulos for select
to authenticated
using (true);

drop policy if exists "clientes_proveedores_company_select" on public.clientes_proveedores;
create policy "clientes_proveedores_company_select"
on public.clientes_proveedores for select
to authenticated
using (id_empresa = (select private.current_empresa_id()));

drop policy if exists "clientes_proveedores_company_write" on public.clientes_proveedores;
create policy "clientes_proveedores_company_write"
on public.clientes_proveedores for all
to authenticated
using (id_empresa = (select private.current_empresa_id()))
with check (id_empresa = (select private.current_empresa_id()));

drop policy if exists "permisos_user_or_admin_select" on public.permisos;
create policy "permisos_user_or_admin_select"
on public.permisos for select
to authenticated
using (
  id_usuario = (select private.current_usuario_id())
  or exists (
    select 1
    from public.usuarios u
    where u.id = permisos.id_usuario
      and u.id_empresa = (select private.current_empresa_id())
      and (select private.is_empresa_admin())
  )
);

drop policy if exists "permisos_admin_write" on public.permisos;
create policy "permisos_admin_write"
on public.permisos for all
to authenticated
using (
  exists (
    select 1
    from public.usuarios u
    where u.id = permisos.id_usuario
      and u.id_empresa = (select private.current_empresa_id())
      and (select private.is_empresa_admin())
  )
)
with check (
  exists (
    select 1
    from public.usuarios u
    where u.id = permisos.id_usuario
      and u.id_empresa = (select private.current_empresa_id())
      and (select private.is_empresa_admin())
  )
);

drop policy if exists "permisos_default_authenticated_select" on public.permisos_dafault;
create policy "permisos_default_authenticated_select"
on public.permisos_dafault for select
to authenticated
using (true);

drop policy if exists "permisos_default_admin_write" on public.permisos_dafault;
create policy "permisos_default_admin_write"
on public.permisos_dafault for all
to authenticated
using ((select private.is_empresa_admin()))
with check ((select private.is_empresa_admin()));

drop policy if exists "crm_planes_company_select" on public.crm_planes;
create policy "crm_planes_company_select"
on public.crm_planes for select
to authenticated
using (
  id_empresa = (select private.current_empresa_id())
  or exists (
    select 1 from public.crm_invitaciones i
    where i.id_empresa = crm_planes.id_empresa
      and lower(i.email) = lower((select auth.jwt() ->> 'email'))
      and i.estado = 'pendiente'
      and i.expires_at > now()
  )
);

drop policy if exists "crm_planes_admin_write" on public.crm_planes;
create policy "crm_planes_admin_write"
on public.crm_planes for all
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "crm_horarios_company_select" on public.crm_horarios;
create policy "crm_horarios_company_select"
on public.crm_horarios for select
to authenticated
using (id_empresa = (select private.current_empresa_id()));

drop policy if exists "crm_horarios_admin_write" on public.crm_horarios;
create policy "crm_horarios_admin_write"
on public.crm_horarios for all
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "clientes_crm_company_or_self_select" on public.clientes_crm;
create policy "clientes_crm_company_or_self_select"
on public.clientes_crm for select
to authenticated
using (
  id_empresa = (select private.current_empresa_id())
  or id_auth = (select auth.uid())
);

drop policy if exists "clientes_crm_company_insert" on public.clientes_crm;
create policy "clientes_crm_company_insert"
on public.clientes_crm for insert
to authenticated
with check (
  id_empresa = (select private.current_empresa_id())
  or (
    id_auth = (select auth.uid())
    and lower(email) = lower((select auth.jwt() ->> 'email'))
    and exists (
      select 1
      from public.crm_invitaciones i
      where i.id_empresa = clientes_crm.id_empresa
        and lower(i.email) = lower(clientes_crm.email)
        and i.estado = 'pendiente'
        and i.expires_at > now()
    )
  )
);

drop policy if exists "clientes_crm_company_or_self_update" on public.clientes_crm;
create policy "clientes_crm_company_or_self_update"
on public.clientes_crm for update
to authenticated
using (
  id_empresa = (select private.current_empresa_id())
  or id_auth = (select auth.uid())
)
with check (
  id_empresa = (select private.current_empresa_id())
  or id_auth = (select auth.uid())
);

drop policy if exists "clientes_crm_admin_delete" on public.clientes_crm;
create policy "clientes_crm_admin_delete"
on public.clientes_crm for delete
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "crm_invitaciones_company_or_recipient_select" on public.crm_invitaciones;
create policy "crm_invitaciones_company_or_recipient_select"
on public.crm_invitaciones for select
to authenticated
using (
  id_empresa = (select private.current_empresa_id())
  or lower(email) = lower((select auth.jwt() ->> 'email'))
);

drop policy if exists "crm_invitaciones_staff_insert" on public.crm_invitaciones;
create policy "crm_invitaciones_staff_insert"
on public.crm_invitaciones for insert
to authenticated
with check (id_empresa = (select private.current_empresa_id()));

drop policy if exists "crm_invitaciones_company_or_recipient_update" on public.crm_invitaciones;
create policy "crm_invitaciones_company_or_recipient_update"
on public.crm_invitaciones for update
to authenticated
using (
  id_empresa = (select private.current_empresa_id())
  or lower(email) = lower((select auth.jwt() ->> 'email'))
)
with check (
  id_empresa = (select private.current_empresa_id())
  or lower(email) = lower((select auth.jwt() ->> 'email'))
);

drop policy if exists "crm_suscripciones_company_or_client_select" on public.crm_suscripciones;
create policy "crm_suscripciones_company_or_client_select"
on public.crm_suscripciones for select
to authenticated
using (
  id_empresa = (select private.current_empresa_id())
  or exists (
    select 1 from public.clientes_crm c
    where c.id = crm_suscripciones.id_cliente_crm
      and c.id_auth = (select auth.uid())
  )
);

drop policy if exists "crm_suscripciones_staff_write" on public.crm_suscripciones;
create policy "crm_suscripciones_staff_write"
on public.crm_suscripciones for all
to authenticated
using (id_empresa = (select private.current_empresa_id()))
with check (id_empresa = (select private.current_empresa_id()));

drop policy if exists "crm_pagos_company_or_client_select" on public.crm_pagos;
create policy "crm_pagos_company_or_client_select"
on public.crm_pagos for select
to authenticated
using (
  id_empresa = (select private.current_empresa_id())
  or exists (
    select 1 from public.clientes_crm c
    where c.id = crm_pagos.id_cliente_crm
      and c.id_auth = (select auth.uid())
  )
);

drop policy if exists "crm_pagos_staff_write" on public.crm_pagos;
create policy "crm_pagos_staff_write"
on public.crm_pagos for all
to authenticated
using (id_empresa = (select private.current_empresa_id()))
with check (id_empresa = (select private.current_empresa_id()));

drop policy if exists "crm_asistencias_company_or_client_select" on public.crm_asistencias;
create policy "crm_asistencias_company_or_client_select"
on public.crm_asistencias for select
to authenticated
using (
  id_empresa = (select private.current_empresa_id())
  or exists (
    select 1 from public.clientes_crm c
    where c.id = crm_asistencias.id_cliente_crm
      and c.id_auth = (select auth.uid())
  )
);

drop policy if exists "crm_asistencias_staff_write" on public.crm_asistencias;
create policy "crm_asistencias_staff_write"
on public.crm_asistencias for all
to authenticated
using (id_empresa = (select private.current_empresa_id()))
with check (id_empresa = (select private.current_empresa_id()));

drop policy if exists "cargos_company_select" on public.cargos;
create policy "cargos_company_select"
on public.cargos for select
to authenticated
using (id_empresa = (select private.current_empresa_id()));

drop policy if exists "cargos_admin_write" on public.cargos;
create policy "cargos_admin_write"
on public.cargos for all
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "trabajadores_company_select" on public.trabajadores;
create policy "trabajadores_company_select"
on public.trabajadores for select
to authenticated
using (id_empresa = (select private.current_empresa_id()));

drop policy if exists "trabajadores_admin_write" on public.trabajadores;
create policy "trabajadores_admin_write"
on public.trabajadores for all
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "empresa_modulos_company_select" on public.empresa_modulos;
create policy "empresa_modulos_company_select"
on public.empresa_modulos for select
to authenticated
using (id_empresa = (select private.current_empresa_id()));

drop policy if exists "empresa_modulos_admin_write" on public.empresa_modulos;
create policy "empresa_modulos_admin_write"
on public.empresa_modulos for all
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "rol_modulos_company_select" on public.rol_modulos;
create policy "rol_modulos_company_select"
on public.rol_modulos for select
to authenticated
using (id_empresa = (select private.current_empresa_id()));

drop policy if exists "rol_modulos_admin_write" on public.rol_modulos;
create policy "rol_modulos_admin_write"
on public.rol_modulos for all
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "parametros_sistema_company_select" on public.parametros_sistema;
create policy "parametros_sistema_company_select"
on public.parametros_sistema for select
to authenticated
using (id_empresa = (select private.current_empresa_id()));

drop policy if exists "parametros_sistema_admin_write" on public.parametros_sistema;
create policy "parametros_sistema_admin_write"
on public.parametros_sistema for all
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

create or replace view public.crm_resumen_clientes
with (security_invoker = true)
as
select
  c.id_empresa,
  count(*)::bigint as total_clientes,
  count(*) filter (where c.estado = 'activo')::bigint as clientes_activos,
  count(*) filter (where c.estado = 'prospecto')::bigint as prospectos,
  count(*) filter (where c.origen = 'invitacion')::bigint as clientes_invitados
from public.clientes_crm c
group by c.id_empresa;

grant select on public.crm_resumen_clientes to authenticated;
revoke all on public.crm_resumen_clientes from anon;

insert into public.modulos (nombre, descripcion, icono, link, etiquetas, "check")
select *
from (
  values
    ('CRM', 'Control de clientes, membresias, pagos y horarios', 'flat-color-icons:conference-call', '/crm', '#default', true),
    ('CRM Clientes', 'Registro manual e invitaciones de clientes', 'flat-color-icons:contacts', '/crm/clientes', '#crm', true),
    ('CRM Pagos', 'Mensualidades, pagos y suscripciones', 'flat-color-icons:paid', '/crm/pagos', '#crm', true),
    ('CRM Horarios', 'Horarios de entrada, salida y asistencia', 'flat-color-icons:calendar', '/crm/horarios', '#crm', true),
    ('Trabajadores', 'Trabajadores, cargos y roles operativos', 'flat-color-icons:businessman', '/crm/trabajadores', '#crm', true),
    ('Permisos CRM', 'Habilitacion de modulos y permisos por rol', 'flat-color-icons:lock', '/crm/permisos', '#crm', true),
    ('Configurar CRM', 'Clientes, pagos, horarios y permisos', 'flat-color-icons:settings', '/configuracion/crm', '#configuracion', true)
) as nuevos(nombre, descripcion, icono, link, etiquetas, "check")
where not exists (
  select 1
  from public.modulos m
  where m.link = nuevos.link
);

-- Keep the browser-facing anon role from reading legacy POS/CRM tables directly.
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke execute on all functions in schema public from anon;
revoke execute on all functions in schema public from public;

grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on all functions in schema public to authenticated;

grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on all functions in schema public to service_role;

-- Final security pass for legacy POS functions and RLS policies.
alter function public.editarmarca(text, integer, integer) set search_path = public;
alter function public.editarcategorias(text, integer, text, integer) set search_path = public;
alter function public.updateuserempresa() set search_path = public;
alter function public.asignarclientegenerico() set search_path = public;
alter function public.detalleventaaumentarstock() set search_path = public;
alter function public.insertarmarca(text, integer) set search_path = public;
alter function public.mostrardetalleventa(integer) set search_path = public;
alter function public.insertarproductos(text, numeric, numeric, integer, text, text, integer, text, boolean, boolean) set search_path = public;
alter function public.editarproductos(integer, text, numeric, numeric, integer, text, text, integer, text, boolean) set search_path = public;
alter function public.mostrarproductos(integer) set search_path = public;
alter function public.updateuseinventariosproductos() set search_path = public;
alter function public.buscarproductos(integer, text) set search_path = public;
alter function public.insertarcategorias(text, text, text, integer) set search_path = public;
alter function public.mostrarsucursalesasignadas(integer) set search_path = public;
alter function public.detalleventastock() set search_path = public;
alter function public.insertardetalleventa(integer, numeric, numeric, numeric, text, integer, numeric, integer, integer) set search_path = public;
alter function public.insertpordefecto() security definer set search_path = public;
alter function public.mostrarempresaxiduser(integer) set search_path = public;

revoke execute on function public.insertpordefecto() from anon, authenticated, public;

do $$
begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    revoke execute on function public.rls_auto_enable() from anon, authenticated, public;
  end if;
end
$$;

alter table public.categorias enable row level security;
drop policy if exists "Enable delete for users based on user_id" on public.categorias;
drop policy if exists "Enable insert for authenticated users only" on public.categorias;
drop policy if exists "Enable read access for all users" on public.categorias;
drop policy if exists "Enable update for users based on email" on public.categorias;
drop policy if exists "categorias_company_select" on public.categorias;
drop policy if exists "categorias_company_insert" on public.categorias;
drop policy if exists "categorias_company_update" on public.categorias;
drop policy if exists "categorias_company_delete" on public.categorias;

create policy "categorias_company_select"
on public.categorias for select
to authenticated
using (id_empresa = (select private.current_empresa_id()));

create policy "categorias_company_insert"
on public.categorias for insert
to authenticated
with check (id_empresa = (select private.current_empresa_id()));

create policy "categorias_company_update"
on public.categorias for update
to authenticated
using (id_empresa = (select private.current_empresa_id()))
with check (id_empresa = (select private.current_empresa_id()));

create policy "categorias_company_delete"
on public.categorias for delete
to authenticated
using (id_empresa = (select private.current_empresa_id()));

notify pgrst, 'reload schema';

-- Performance pass for RLS policies: cache auth email and avoid SELECT overlap
-- from FOR ALL write policies.
create or replace function private.current_auth_email()
returns text
language sql
stable
set search_path = ''
as $$
  select lower((auth.jwt() ->> 'email')::text)
$$;

revoke execute on function private.current_auth_email() from public, anon;
grant execute on function private.current_auth_email() to authenticated;

drop policy if exists "crm_planes_company_select" on public.crm_planes;
create policy "crm_planes_company_select"
on public.crm_planes for select
to authenticated
using (
  id_empresa = (select private.current_empresa_id())
  or exists (
    select 1 from public.crm_invitaciones i
    where i.id_empresa = crm_planes.id_empresa
      and lower(i.email) = (select private.current_auth_email())
      and i.estado = 'pendiente'
      and i.expires_at > now()
  )
);

drop policy if exists "clientes_crm_company_insert" on public.clientes_crm;
create policy "clientes_crm_company_insert"
on public.clientes_crm for insert
to authenticated
with check (
  id_empresa = (select private.current_empresa_id())
  or (
    id_auth = (select auth.uid())
    and lower(email) = (select private.current_auth_email())
    and exists (
      select 1 from public.crm_invitaciones i
      where i.id_empresa = clientes_crm.id_empresa
        and lower(i.email) = lower(clientes_crm.email)
        and i.estado = 'pendiente'
        and i.expires_at > now()
    )
  )
);

drop policy if exists "crm_invitaciones_company_or_recipient_select" on public.crm_invitaciones;
create policy "crm_invitaciones_company_or_recipient_select"
on public.crm_invitaciones for select
to authenticated
using (
  id_empresa = (select private.current_empresa_id())
  or lower(email) = (select private.current_auth_email())
);

drop policy if exists "crm_invitaciones_company_or_recipient_update" on public.crm_invitaciones;
create policy "crm_invitaciones_company_or_recipient_update"
on public.crm_invitaciones for update
to authenticated
using (
  id_empresa = (select private.current_empresa_id())
  or lower(email) = (select private.current_auth_email())
)
with check (
  id_empresa = (select private.current_empresa_id())
  or lower(email) = (select private.current_auth_email())
);

create or replace function private.replace_write_policy_set(
  target_table regclass,
  old_policy text,
  policy_base text,
  predicate text
)
returns void
language plpgsql
set search_path = ''
as $$
begin
  execute format('drop policy if exists %I on %s', old_policy, target_table);
  execute format('drop policy if exists %I on %s', policy_base || '_insert', target_table);
  execute format('drop policy if exists %I on %s', policy_base || '_update', target_table);
  execute format('drop policy if exists %I on %s', policy_base || '_delete', target_table);

  execute format(
    'create policy %I on %s for insert to authenticated with check (%s)',
    policy_base || '_insert',
    target_table,
    predicate
  );
  execute format(
    'create policy %I on %s for update to authenticated using (%s) with check (%s)',
    policy_base || '_update',
    target_table,
    predicate,
    predicate
  );
  execute format(
    'create policy %I on %s for delete to authenticated using (%s)',
    policy_base || '_delete',
    target_table,
    predicate
  );
end
$$;

select private.replace_write_policy_set('public.cargos', 'cargos_admin_write', 'cargos_admin', 'id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin())');
select private.replace_write_policy_set('public.clientes_proveedores', 'clientes_proveedores_company_write', 'clientes_proveedores_company', 'id_empresa = (select private.current_empresa_id())');
select private.replace_write_policy_set('public.crm_asistencias', 'crm_asistencias_staff_write', 'crm_asistencias_staff', 'id_empresa = (select private.current_empresa_id())');
select private.replace_write_policy_set('public.crm_horarios', 'crm_horarios_admin_write', 'crm_horarios_admin', 'id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin())');
select private.replace_write_policy_set('public.crm_pagos', 'crm_pagos_staff_write', 'crm_pagos_staff', 'id_empresa = (select private.current_empresa_id())');
select private.replace_write_policy_set('public.crm_planes', 'crm_planes_admin_write', 'crm_planes_admin', 'id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin())');
select private.replace_write_policy_set('public.crm_suscripciones', 'crm_suscripciones_staff_write', 'crm_suscripciones_staff', 'id_empresa = (select private.current_empresa_id())');
select private.replace_write_policy_set('public.empresa_modulos', 'empresa_modulos_admin_write', 'empresa_modulos_admin', 'id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin())');
select private.replace_write_policy_set('public.parametros_sistema', 'parametros_sistema_admin_write', 'parametros_sistema_admin', 'id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin())');
select private.replace_write_policy_set('public.permisos', 'permisos_admin_write', 'permisos_admin', 'exists (select 1 from public.usuarios u where u.id = permisos.id_usuario and u.id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))');
select private.replace_write_policy_set('public.permisos_dafault', 'permisos_default_admin_write', 'permisos_default_admin', '(select private.is_empresa_admin())');
select private.replace_write_policy_set('public.rol_modulos', 'rol_modulos_admin_write', 'rol_modulos_admin', 'id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin())');
select private.replace_write_policy_set('public.trabajadores', 'trabajadores_admin_write', 'trabajadores_admin', 'id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin())');

drop function private.replace_write_policy_set(regclass, text, text, text);

notify pgrst, 'reload schema';
