alter table public.asignacion_sucursal
  add column if not exists id_caja bigint;

alter table public.ventas
  add column if not exists id_cierre_caja bigint;

create table if not exists public.metodos_pago (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  nombre text not null,
  icono text not null default '-',
  color text,
  delete_update boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists metodos_pago_empresa_nombre_uidx
  on public.metodos_pago (id_empresa, lower(nombre));

create table if not exists public.caja (
  id bigint generated by default as identity primary key,
  id_sucursal bigint not null references public.sucursales(id) on delete cascade,
  descripcion text not null,
  estado text not null default 'activa' check (estado in ('activa', 'inactiva')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists caja_sucursal_descripcion_uidx
  on public.caja (id_sucursal, lower(descripcion));

create table if not exists public.cierrecaja (
  id bigint generated by default as identity primary key,
  fechainicio timestamptz not null default now(),
  fechacierre timestamptz,
  id_usuario bigint references public.usuarios(id) on delete set null,
  id_caja bigint not null references public.caja(id) on delete cascade,
  estado integer not null default 0 check (estado in (0, 1)),
  total_efectivo_calculado numeric(12,2) not null default 0,
  total_efectivo_real numeric(12,2) not null default 0,
  diferencia_efectivo numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cierrecaja_caja_estado_idx
  on public.cierrecaja (id_caja, estado);

create unique index if not exists cierrecaja_caja_abierta_uidx
  on public.cierrecaja (id_caja)
  where estado = 0;

create table if not exists public.movimientos_caja (
  id bigint generated by default as identity primary key,
  fecha_movimiento timestamptz not null default now(),
  tipo_movimiento text not null check (tipo_movimiento in ('apertura', 'ingreso', 'salida', 'cierre')),
  monto numeric(12,2) not null default 0 check (monto >= 0),
  id_metodo_pago bigint references public.metodos_pago(id) on delete set null,
  descripcion text,
  id_usuario bigint references public.usuarios(id) on delete set null,
  id_cierre_caja bigint not null references public.cierrecaja(id) on delete cascade,
  id_ventas bigint references public.ventas(id) on delete set null,
  vuelto numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists movimientos_caja_cierre_fecha_idx
  on public.movimientos_caja (id_cierre_caja, fecha_movimiento desc);

create table if not exists public.impresoras (
  id bigint generated by default as identity primary key,
  id_caja bigint not null references public.caja(id) on delete cascade,
  state boolean not null default false,
  pc_name text not null default '-',
  ip_local text not null default '-',
  name text not null default '-',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_caja)
);

create table if not exists public.tipo_comprobantes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  destino text not null default 'ventas',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (nombre, destino)
);

create table if not exists public.serializacion_comprobantes (
  id bigint generated by default as identity primary key,
  sucursal_id bigint not null references public.sucursales(id) on delete cascade,
  id_tipo_comprobante bigint not null references public.tipo_comprobantes(id) on delete restrict,
  serie text not null default 'A001',
  correlativo bigint not null default 1,
  cantidad_numeros integer not null default 8 check (cantidad_numeros > 0),
  por_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (sucursal_id, id_tipo_comprobante)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'asignacion_sucursal_id_caja_fkey'
      and conrelid = 'public.asignacion_sucursal'::regclass
  ) then
    alter table public.asignacion_sucursal
      add constraint asignacion_sucursal_id_caja_fkey
      foreign key (id_caja) references public.caja(id) on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'ventas_id_cierre_caja_fkey'
      and conrelid = 'public.ventas'::regclass
  ) then
    alter table public.ventas
      add constraint ventas_id_cierre_caja_fkey
      foreign key (id_cierre_caja) references public.cierrecaja(id) on delete set null;
  end if;
end;
$$;

create or replace function private.ensure_pos_defaults_for_empresa()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  default_sucursal_id bigint;
  default_caja_id bigint;
begin
  if new.id is null then
    return new;
  end if;

  insert into public.sucursales (nombre, direccion_fiscal, id_empresa, simbolo_moneda)
  select 'Principal', coalesce(new.direccion_fiscal, '-'), new.id, coalesce(new.simbolo_moneda, '$')
  where not exists (
    select 1 from public.sucursales s where s.id_empresa = new.id
  )
  returning id into default_sucursal_id;

  if default_sucursal_id is null then
    select s.id
    into default_sucursal_id
    from public.sucursales s
    where s.id_empresa = new.id
    order by s.id
    limit 1;
  end if;

  insert into public.metodos_pago (id_empresa, nombre, icono, color, delete_update)
  select new.id, seed.nombre, '-', seed.color, seed.delete_update
  from (values
    ('Efectivo', '#16a34a', false),
    ('Tarjeta', '#2563eb', true),
    ('Transferencia', '#7c3aed', true),
    ('Mixto', '#f59e0b', false)
  ) as seed(nombre, color, delete_update)
  where not exists (
    select 1
    from public.metodos_pago mp
    where mp.id_empresa = new.id
      and lower(mp.nombre) = lower(seed.nombre)
  );

  if default_sucursal_id is not null then
    insert into public.caja (id_sucursal, descripcion)
    select default_sucursal_id, 'Caja principal'
    where not exists (
      select 1 from public.caja c where c.id_sucursal = default_sucursal_id
    )
    returning id into default_caja_id;

    if default_caja_id is null then
      select c.id
      into default_caja_id
      from public.caja c
      where c.id_sucursal = default_sucursal_id
      order by c.id
      limit 1;
    end if;

    if default_caja_id is not null then
      insert into public.impresoras (id_caja)
      values (default_caja_id)
      on conflict (id_caja) do nothing;

      if new.id_usuario is not null then
        insert into public.asignacion_sucursal (id_sucursal, id_usuario, id_caja)
        select default_sucursal_id, new.id_usuario, default_caja_id
        where not exists (
          select 1
          from public.asignacion_sucursal a
          where a.id_usuario = new.id_usuario
            and a.id_sucursal = default_sucursal_id
        );
      end if;
    end if;
  end if;

  return new;
end;
$$;

revoke all on function private.ensure_pos_defaults_for_empresa() from public, anon, authenticated;

drop trigger if exists trg_empresa_pos_defaults on public.empresa;
create trigger trg_empresa_pos_defaults
after insert or update of id_usuario on public.empresa
for each row execute function private.ensure_pos_defaults_for_empresa();

create or replace function private.ensure_impresora_for_caja()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.impresoras (id_caja)
  values (new.id)
  on conflict (id_caja) do nothing;
  return new;
end;
$$;

revoke all on function private.ensure_impresora_for_caja() from public, anon, authenticated;

drop trigger if exists trg_caja_impresora_default on public.caja;
create trigger trg_caja_impresora_default
after insert on public.caja
for each row execute function private.ensure_impresora_for_caja();

drop trigger if exists trg_metodos_pago_updated_at on public.metodos_pago;
create trigger trg_metodos_pago_updated_at
before update on public.metodos_pago
for each row execute function private.set_updated_at();

drop trigger if exists trg_caja_updated_at on public.caja;
create trigger trg_caja_updated_at
before update on public.caja
for each row execute function private.set_updated_at();

drop trigger if exists trg_cierrecaja_updated_at on public.cierrecaja;
create trigger trg_cierrecaja_updated_at
before update on public.cierrecaja
for each row execute function private.set_updated_at();

drop trigger if exists trg_movimientos_caja_updated_at on public.movimientos_caja;
create trigger trg_movimientos_caja_updated_at
before update on public.movimientos_caja
for each row execute function private.set_updated_at();

drop trigger if exists trg_impresoras_updated_at on public.impresoras;
create trigger trg_impresoras_updated_at
before update on public.impresoras
for each row execute function private.set_updated_at();

drop trigger if exists trg_tipo_comprobantes_updated_at on public.tipo_comprobantes;
create trigger trg_tipo_comprobantes_updated_at
before update on public.tipo_comprobantes
for each row execute function private.set_updated_at();

drop trigger if exists trg_serializacion_comprobantes_updated_at on public.serializacion_comprobantes;
create trigger trg_serializacion_comprobantes_updated_at
before update on public.serializacion_comprobantes
for each row execute function private.set_updated_at();

alter table public.metodos_pago enable row level security;
alter table public.caja enable row level security;
alter table public.cierrecaja enable row level security;
alter table public.movimientos_caja enable row level security;
alter table public.impresoras enable row level security;
alter table public.tipo_comprobantes enable row level security;
alter table public.serializacion_comprobantes enable row level security;

grant select, insert, update, delete on
  public.metodos_pago,
  public.caja,
  public.cierrecaja,
  public.movimientos_caja,
  public.impresoras,
  public.serializacion_comprobantes
to authenticated;

grant select on public.tipo_comprobantes to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on
  public.metodos_pago,
  public.caja,
  public.cierrecaja,
  public.movimientos_caja,
  public.impresoras,
  public.tipo_comprobantes,
  public.serializacion_comprobantes
from anon;

drop policy if exists "metodos_pago_company_select" on public.metodos_pago;
create policy "metodos_pago_company_select"
on public.metodos_pago for select
to authenticated
using (id_empresa = (select private.current_empresa_id()));

drop policy if exists "metodos_pago_admin_write" on public.metodos_pago;
create policy "metodos_pago_admin_write"
on public.metodos_pago for all
to authenticated
using (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()))
with check (id_empresa = (select private.current_empresa_id()) and (select private.is_empresa_admin()));

drop policy if exists "caja_company_select" on public.caja;
create policy "caja_company_select"
on public.caja for select
to authenticated
using (
  exists (
    select 1 from public.sucursales s
    where s.id = caja.id_sucursal
      and s.id_empresa = (select private.current_empresa_id())
  )
);

drop policy if exists "caja_admin_write" on public.caja;
create policy "caja_admin_write"
on public.caja for all
to authenticated
using (
  exists (
    select 1 from public.sucursales s
    where s.id = caja.id_sucursal
      and s.id_empresa = (select private.current_empresa_id())
      and (select private.is_empresa_admin())
  )
)
with check (
  exists (
    select 1 from public.sucursales s
    where s.id = caja.id_sucursal
      and s.id_empresa = (select private.current_empresa_id())
      and (select private.is_empresa_admin())
  )
);

drop policy if exists "cierrecaja_company_select" on public.cierrecaja;
create policy "cierrecaja_company_select"
on public.cierrecaja for select
to authenticated
using (
  exists (
    select 1
    from public.caja c
    join public.sucursales s on s.id = c.id_sucursal
    where c.id = cierrecaja.id_caja
      and s.id_empresa = (select private.current_empresa_id())
  )
);

drop policy if exists "cierrecaja_staff_write" on public.cierrecaja;
create policy "cierrecaja_staff_write"
on public.cierrecaja for all
to authenticated
using (
  exists (
    select 1
    from public.caja c
    join public.sucursales s on s.id = c.id_sucursal
    where c.id = cierrecaja.id_caja
      and s.id_empresa = (select private.current_empresa_id())
  )
)
with check (
  exists (
    select 1
    from public.caja c
    join public.sucursales s on s.id = c.id_sucursal
    where c.id = cierrecaja.id_caja
      and s.id_empresa = (select private.current_empresa_id())
  )
);

drop policy if exists "movimientos_caja_company_select" on public.movimientos_caja;
create policy "movimientos_caja_company_select"
on public.movimientos_caja for select
to authenticated
using (
  exists (
    select 1
    from public.cierrecaja cc
    join public.caja c on c.id = cc.id_caja
    join public.sucursales s on s.id = c.id_sucursal
    where cc.id = movimientos_caja.id_cierre_caja
      and s.id_empresa = (select private.current_empresa_id())
  )
);

drop policy if exists "movimientos_caja_staff_write" on public.movimientos_caja;
create policy "movimientos_caja_staff_write"
on public.movimientos_caja for all
to authenticated
using (
  exists (
    select 1
    from public.cierrecaja cc
    join public.caja c on c.id = cc.id_caja
    join public.sucursales s on s.id = c.id_sucursal
    where cc.id = movimientos_caja.id_cierre_caja
      and s.id_empresa = (select private.current_empresa_id())
  )
)
with check (
  exists (
    select 1
    from public.cierrecaja cc
    join public.caja c on c.id = cc.id_caja
    join public.sucursales s on s.id = c.id_sucursal
    where cc.id = movimientos_caja.id_cierre_caja
      and s.id_empresa = (select private.current_empresa_id())
  )
);

drop policy if exists "impresoras_company_select" on public.impresoras;
create policy "impresoras_company_select"
on public.impresoras for select
to authenticated
using (
  exists (
    select 1
    from public.caja c
    join public.sucursales s on s.id = c.id_sucursal
    where c.id = impresoras.id_caja
      and s.id_empresa = (select private.current_empresa_id())
  )
);

drop policy if exists "impresoras_company_update" on public.impresoras;
create policy "impresoras_company_update"
on public.impresoras for update
to authenticated
using (
  exists (
    select 1
    from public.caja c
    join public.sucursales s on s.id = c.id_sucursal
    where c.id = impresoras.id_caja
      and s.id_empresa = (select private.current_empresa_id())
  )
)
with check (
  exists (
    select 1
    from public.caja c
    join public.sucursales s on s.id = c.id_sucursal
    where c.id = impresoras.id_caja
      and s.id_empresa = (select private.current_empresa_id())
  )
);

drop policy if exists "tipo_comprobantes_authenticated_select" on public.tipo_comprobantes;
create policy "tipo_comprobantes_authenticated_select"
on public.tipo_comprobantes for select
to authenticated
using (true);

drop policy if exists "serializacion_company_select" on public.serializacion_comprobantes;
create policy "serializacion_company_select"
on public.serializacion_comprobantes for select
to authenticated
using (
  exists (
    select 1 from public.sucursales s
    where s.id = serializacion_comprobantes.sucursal_id
      and s.id_empresa = (select private.current_empresa_id())
  )
);

drop policy if exists "serializacion_admin_update" on public.serializacion_comprobantes;
drop policy if exists "serializacion_company_update" on public.serializacion_comprobantes;
create policy "serializacion_company_update"
on public.serializacion_comprobantes for update
to authenticated
using (
  exists (
    select 1 from public.sucursales s
    where s.id = serializacion_comprobantes.sucursal_id
      and s.id_empresa = (select private.current_empresa_id())
  )
)
with check (
  exists (
    select 1 from public.sucursales s
    where s.id = serializacion_comprobantes.sucursal_id
      and s.id_empresa = (select private.current_empresa_id())
  )
);

insert into public.tipo_comprobantes (nombre, destino)
select seed.nombre, seed.destino
from (values ('Recibo', 'ventas'), ('Factura', 'ventas')) as seed(nombre, destino)
where not exists (
  select 1
  from public.tipo_comprobantes tc
  where lower(tc.nombre) = lower(seed.nombre)
    and tc.destino = seed.destino
);

insert into public.sucursales (nombre, direccion_fiscal, id_empresa, simbolo_moneda)
select 'Principal', coalesce(e.direccion_fiscal, '-'), e.id, coalesce(e.simbolo_moneda, '$')
from public.empresa e
where not exists (
  select 1 from public.sucursales s where s.id_empresa = e.id
);

insert into public.metodos_pago (id_empresa, nombre, icono, color, delete_update)
select e.id, seed.nombre, '-', seed.color, seed.delete_update
from public.empresa e
cross join (values
  ('Efectivo', '#16a34a', false),
  ('Tarjeta', '#2563eb', true),
  ('Transferencia', '#7c3aed', true),
  ('Mixto', '#f59e0b', false)
) as seed(nombre, color, delete_update)
where not exists (
  select 1
  from public.metodos_pago mp
  where mp.id_empresa = e.id
    and lower(mp.nombre) = lower(seed.nombre)
);

insert into public.caja (id_sucursal, descripcion)
select s.id, 'Caja principal'
from public.sucursales s
where not exists (
  select 1 from public.caja c where c.id_sucursal = s.id
);

insert into public.impresoras (id_caja)
select c.id
from public.caja c
where not exists (
  select 1 from public.impresoras i where i.id_caja = c.id
);

update public.asignacion_sucursal a
set id_caja = c.id
from public.caja c
where c.id_sucursal = a.id_sucursal
  and a.id_caja is null;

insert into public.asignacion_sucursal (id_sucursal, id_usuario, id_caja)
select s.id, u.id, c.id
from public.usuarios u
join public.sucursales s on s.id_empresa = u.id_empresa
join public.caja c on c.id_sucursal = s.id
where u.id_empresa is not null
  and not exists (
    select 1
    from public.asignacion_sucursal a
    where a.id_usuario = u.id
      and a.id_sucursal = s.id
  );

insert into public.serializacion_comprobantes (
  sucursal_id,
  id_tipo_comprobante,
  serie,
  correlativo,
  cantidad_numeros,
  por_default
)
select s.id, tc.id, 'A001', 1, 8, true
from public.sucursales s
join public.tipo_comprobantes tc on tc.nombre = 'Recibo' and tc.destino = 'ventas'
where not exists (
  select 1
  from public.serializacion_comprobantes sc
  where sc.sucursal_id = s.id
    and sc.id_tipo_comprobante = tc.id
);

create or replace function public.setdefaultserializacion(_id bigint, _id_sucursal bigint)
returns void
language plpgsql
set search_path = public
as $$
begin
  update public.serializacion_comprobantes
  set por_default = false
  where sucursal_id = _id_sucursal;

  update public.serializacion_comprobantes
  set por_default = true
  where id = _id
    and sucursal_id = _id_sucursal;
end;
$$;

create or replace function public.dashboartotalventasconfechas(
  _id_empresa integer,
  _fecha_inicio date default null,
  _fecha_fin date default null
)
returns table(fecha date, total_ventas numeric)
language sql
stable
set search_path = public
as $$
  select v.fecha::date as fecha, coalesce(sum(v.monto_total), 0)::numeric as total_ventas
  from public.ventas v
  where v.id_empresa = _id_empresa
    and (_fecha_inicio is null or v.fecha >= _fecha_inicio)
    and (_fecha_fin is null or v.fecha <= _fecha_fin)
    and coalesce(v.estado, '') <> 'pendiente'
  group by v.fecha::date
  order by v.fecha::date;
$$;

create or replace function public.dashboardsumarcantidaddetalleventa(
  _id_empresa integer,
  _fecha_inicio date default null,
  _fecha_fin date default null
)
returns numeric
language sql
stable
set search_path = public
as $$
  select coalesce(sum(dv.cantidad), 0)::numeric
  from public.detalle_venta dv
  join public.ventas v on v.id = dv.id_venta
  where v.id_empresa = _id_empresa
    and (_fecha_inicio is null or v.fecha >= _fecha_inicio)
    and (_fecha_fin is null or v.fecha <= _fecha_fin)
    and coalesce(v.estado, '') <> 'pendiente';
$$;

create or replace function public.dashboardsumargananciadetalleventa(
  _id_empresa integer,
  _fecha_inicio date default null,
  _fecha_fin date default null
)
returns numeric
language sql
stable
set search_path = public
as $$
  select coalesce(sum((coalesce(dv.precio_venta, 0) - coalesce(dv.precio_compra, 0)) * coalesce(dv.cantidad, 0)), 0)::numeric
  from public.detalle_venta dv
  join public.ventas v on v.id = dv.id_venta
  where v.id_empresa = _id_empresa
    and (_fecha_inicio is null or v.fecha >= _fecha_inicio)
    and (_fecha_fin is null or v.fecha <= _fecha_fin)
    and coalesce(v.estado, '') <> 'pendiente';
$$;

create or replace function public.dashboardsumarventasporempresaperiodoanterior(
  _id_empresa integer,
  _fecha_inicio date default null,
  _fecha_fin date default null
)
returns numeric
language sql
stable
set search_path = public
as $$
  select coalesce(sum(v.monto_total), 0)::numeric
  from public.ventas v
  where v.id_empresa = _id_empresa
    and (_fecha_inicio is null or v.fecha >= _fecha_inicio)
    and (_fecha_fin is null or v.fecha <= _fecha_fin)
    and coalesce(v.estado, '') <> 'pendiente';
$$;

create or replace function public.mostrartop5productosmasvendidosxcantidad(
  _id_empresa integer,
  _fecha_inicio date default null,
  _fecha_fin date default null
)
returns table(nombre_producto text, total_vendido numeric, porcentaje numeric)
language sql
stable
set search_path = public
as $$
  with ventas_producto as (
    select
      coalesce(p.nombre, dv.descripcion, 'Producto') as nombre_producto,
      sum(coalesce(dv.cantidad, 0))::numeric as total_vendido
    from public.detalle_venta dv
    join public.ventas v on v.id = dv.id_venta
    left join public.productos p on p.id = dv.id_producto
    where v.id_empresa = _id_empresa
      and (_fecha_inicio is null or v.fecha >= _fecha_inicio)
      and (_fecha_fin is null or v.fecha <= _fecha_fin)
      and coalesce(v.estado, '') <> 'pendiente'
    group by coalesce(p.nombre, dv.descripcion, 'Producto')
  ),
  total as (
    select nullif(sum(total_vendido), 0) as valor from ventas_producto
  )
  select
    vp.nombre_producto,
    vp.total_vendido,
    round((vp.total_vendido / total.valor) * 100, 2) as porcentaje
  from ventas_producto vp
  cross join total
  where total.valor is not null
  order by vp.total_vendido desc, vp.nombre_producto
  limit 5;
$$;

create or replace function public.mostrartop10productosmasvendidosxmonto(
  _id_empresa integer,
  _fecha_inicio date default null,
  _fecha_fin date default null
)
returns table(nombre_producto text, total_vendido numeric, porcentaje numeric)
language sql
stable
set search_path = public
as $$
  with ventas_producto as (
    select
      coalesce(p.nombre, dv.descripcion, 'Producto') as nombre_producto,
      sum(coalesce(dv.total, coalesce(dv.precio_venta, 0) * coalesce(dv.cantidad, 0)))::numeric as total_vendido
    from public.detalle_venta dv
    join public.ventas v on v.id = dv.id_venta
    left join public.productos p on p.id = dv.id_producto
    where v.id_empresa = _id_empresa
      and (_fecha_inicio is null or v.fecha >= _fecha_inicio)
      and (_fecha_fin is null or v.fecha <= _fecha_fin)
      and coalesce(v.estado, '') <> 'pendiente'
    group by coalesce(p.nombre, dv.descripcion, 'Producto')
  ),
  total as (
    select nullif(sum(total_vendido), 0) as valor from ventas_producto
  )
  select
    vp.nombre_producto,
    vp.total_vendido,
    round((vp.total_vendido / total.valor) * 100, 2) as porcentaje
  from ventas_producto vp
  cross join total
  where total.valor is not null
  order by vp.total_vendido desc, vp.nombre_producto
  limit 10;
$$;

create or replace function public.mostrarmovimientoscajalive(_id_empresa integer)
returns table(
  fecha_movimiento timestamptz,
  caja_nombre text,
  tipo_movimiento text,
  usuario_nombre text,
  monto numeric
)
language sql
stable
set search_path = public
as $$
  select
    mc.fecha_movimiento,
    c.descripcion as caja_nombre,
    mc.tipo_movimiento,
    coalesce(u.nombres, '-') as usuario_nombre,
    mc.monto
  from public.movimientos_caja mc
  join public.cierrecaja cc on cc.id = mc.id_cierre_caja
  join public.caja c on c.id = cc.id_caja
  join public.sucursales s on s.id = c.id_sucursal
  left join public.usuarios u on u.id = mc.id_usuario
  where s.id_empresa = _id_empresa
  order by mc.fecha_movimiento desc
  limit 20;
$$;

create or replace function public.sumarefectivosinventasmovcierrecaja(_id_cierre_caja bigint)
returns table(tipo_movimiento text, monto numeric)
language sql
stable
set search_path = public
as $$
  select mc.tipo_movimiento, coalesce(mc.monto, 0)::numeric as monto
  from public.movimientos_caja mc
  where mc.id_cierre_caja = _id_cierre_caja
    and mc.tipo_movimiento in ('apertura', 'ingreso', 'salida')
    and mc.id_ventas is null
  order by mc.fecha_movimiento asc;
$$;

create or replace function public.sumarventasmetodopagomovcierrecaja(_id_cierre_caja bigint)
returns table(metodo_pago text, monto numeric)
language sql
stable
set search_path = public
as $$
  select coalesce(mp.nombre, 'Sin metodo') as metodo_pago, coalesce(sum(mc.monto), 0)::numeric as monto
  from public.movimientos_caja mc
  left join public.metodos_pago mp on mp.id = mc.id_metodo_pago
  where mc.id_cierre_caja = _id_cierre_caja
    and mc.tipo_movimiento = 'ingreso'
    and mc.id_ventas is not null
  group by coalesce(mp.nombre, 'Sin metodo')
  order by metodo_pago;
$$;

create or replace function public.mostrarcajasabiertasporempresa(_id_empresa integer)
returns table(
  id bigint,
  id_caja bigint,
  fechainicio timestamptz,
  fechacierre timestamptz,
  estado integer,
  usuario text,
  rol text,
  caja_nombre text,
  sucursal text
)
language sql
stable
set search_path = public
as $$
  select
    cc.id,
    cc.id_caja,
    cc.fechainicio,
    cc.fechacierre,
    cc.estado,
    coalesce(u.nombres, '-') as usuario,
    coalesce(r.nombre, '-') as rol,
    c.descripcion as caja_nombre,
    s.nombre as sucursal
  from public.cierrecaja cc
  join public.caja c on c.id = cc.id_caja
  join public.sucursales s on s.id = c.id_sucursal
  left join public.usuarios u on u.id = cc.id_usuario
  left join public.roles r on r.id = u.id_rol
  where s.id_empresa = _id_empresa
    and cc.estado = 0
  order by cc.fechainicio desc;
$$;

create or replace function public.confirmar_venta(
  _id_venta bigint,
  _id_usuario bigint,
  _vuelto numeric,
  _id_tipo_comprobante bigint,
  _serie text,
  _id_sucursal bigint,
  _id_cliente bigint,
  _fecha date,
  _monto_total numeric
)
returns setof public.ventas
language plpgsql
set search_path = public
as $$
begin
  update public.ventas
  set
    fecha = coalesce(_fecha, current_date),
    id_usuario = _id_usuario,
    id_sucursal = _id_sucursal,
    id_cliente = _id_cliente,
    monto_total = coalesce(_monto_total, 0),
    sub_total = coalesce(_monto_total, 0),
    vuelto = coalesce(_vuelto, 0),
    estado = 'confirmada',
    cantidad_productos = (
      select coalesce(sum(dv.cantidad), 0)::bigint
      from public.detalle_venta dv
      where dv.id_venta = _id_venta
    )
  where id = _id_venta;

  update public.detalle_venta
  set estado = 'confirmada'
  where id_venta = _id_venta;

  update public.serializacion_comprobantes
  set correlativo = correlativo + 1
  where id_tipo_comprobante = _id_tipo_comprobante
    and sucursal_id = _id_sucursal
    and serie = _serie;

  return query
  select *
  from public.ventas
  where id = _id_venta;
end;
$$;

revoke all on function public.setdefaultserializacion(bigint, bigint) from public, anon;
revoke all on function public.dashboartotalventasconfechas(integer, date, date) from public, anon;
revoke all on function public.dashboardsumarcantidaddetalleventa(integer, date, date) from public, anon;
revoke all on function public.dashboardsumargananciadetalleventa(integer, date, date) from public, anon;
revoke all on function public.dashboardsumarventasporempresaperiodoanterior(integer, date, date) from public, anon;
revoke all on function public.mostrartop5productosmasvendidosxcantidad(integer, date, date) from public, anon;
revoke all on function public.mostrartop10productosmasvendidosxmonto(integer, date, date) from public, anon;
revoke all on function public.mostrarmovimientoscajalive(integer) from public, anon;
revoke all on function public.sumarefectivosinventasmovcierrecaja(bigint) from public, anon;
revoke all on function public.sumarventasmetodopagomovcierrecaja(bigint) from public, anon;
revoke all on function public.mostrarcajasabiertasporempresa(integer) from public, anon;
revoke all on function public.confirmar_venta(bigint, bigint, numeric, bigint, text, bigint, bigint, date, numeric) from public, anon;

grant execute on function public.setdefaultserializacion(bigint, bigint) to authenticated;
grant execute on function public.dashboartotalventasconfechas(integer, date, date) to authenticated;
grant execute on function public.dashboardsumarcantidaddetalleventa(integer, date, date) to authenticated;
grant execute on function public.dashboardsumargananciadetalleventa(integer, date, date) to authenticated;
grant execute on function public.dashboardsumarventasporempresaperiodoanterior(integer, date, date) to authenticated;
grant execute on function public.mostrartop5productosmasvendidosxcantidad(integer, date, date) to authenticated;
grant execute on function public.mostrartop10productosmasvendidosxmonto(integer, date, date) to authenticated;
grant execute on function public.mostrarmovimientoscajalive(integer) to authenticated;
grant execute on function public.sumarefectivosinventasmovcierrecaja(bigint) to authenticated;
grant execute on function public.sumarventasmetodopagomovcierrecaja(bigint) to authenticated;
grant execute on function public.mostrarcajasabiertasporempresa(integer) to authenticated;
grant execute on function public.confirmar_venta(bigint, bigint, numeric, bigint, text, bigint, bigint, date, numeric) to authenticated;
