-- Atomic CRM workflows for plan-backed invitations, subscription lifecycle,
-- billing of existing memberships, and fast daily attendance.

alter table public.clientes_crm
  add column if not exists id_horario bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'clientes_crm_id_horario_fkey'
      and conrelid = 'public.clientes_crm'::regclass
  ) then
    alter table public.clientes_crm
      add constraint clientes_crm_id_horario_fkey
      foreign key (id_horario)
      references public.crm_horarios(id)
      on delete set null;
  end if;
end
$$;

create index if not exists clientes_crm_id_horario_idx
  on public.clientes_crm (id_horario)
  where id_horario is not null;

update public.clientes_crm
set codigo = 'CLI-' || lpad(id::text, 6, '0')
where codigo is null or btrim(codigo) = '';

create unique index if not exists crm_asistencias_empresa_cliente_fecha_uidx
  on public.crm_asistencias (id_empresa, id_cliente_crm, fecha);

-- Historical invitations without a plan remain available for audit, but no
-- pending/accepted invitation can exist without a selected plan from now on.
update public.crm_invitaciones
set
  estado = 'expirada',
  estado_envio = case
    when estado_envio = 'enviando' then 'error'
    else estado_envio
  end,
  ultimo_error_email = coalesce(
    ultimo_error_email,
    'Invitación histórica cerrada porque no tenía un plan asignado.'
  )
where id_plan is null
  and estado = 'pendiente';

alter table public.crm_invitaciones
  drop constraint if exists crm_invitaciones_id_plan_fkey;

alter table public.crm_invitaciones
  add constraint crm_invitaciones_id_plan_fkey
  foreign key (id_plan)
  references public.crm_planes(id)
  on delete restrict;

alter table public.crm_invitaciones
  drop constraint if exists crm_invitaciones_plan_obligatorio_check;

alter table public.crm_invitaciones
  add constraint crm_invitaciones_plan_obligatorio_check
  check (
    id_plan is not null
    or estado in ('expirada', 'cancelada')
  );

create table if not exists public.crm_suscripcion_historial (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  id_suscripcion bigint not null references public.crm_suscripciones(id) on delete cascade,
  accion text not null
    check (accion in ('asignada', 'cambio_plan', 'renovada', 'pausada', 'reactivada', 'cancelada', 'invitacion_aceptada')),
  id_plan_anterior bigint references public.crm_planes(id) on delete set null,
  id_plan_nuevo bigint references public.crm_planes(id) on delete set null,
  fecha_inicio_anterior date,
  fecha_fin_anterior date,
  fecha_inicio_nueva date,
  fecha_fin_nueva date,
  estado_anterior text,
  estado_nuevo text,
  registrado_por bigint references public.usuarios(id) on delete set null,
  detalle jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.crm_suscripcion_historial enable row level security;

create index if not exists crm_suscripcion_historial_empresa_created_idx
  on public.crm_suscripcion_historial (id_empresa, created_at desc);

create index if not exists crm_suscripcion_historial_suscripcion_created_idx
  on public.crm_suscripcion_historial (id_suscripcion, created_at desc);

create index if not exists crm_suscripcion_historial_plan_anterior_idx
  on public.crm_suscripcion_historial (id_plan_anterior)
  where id_plan_anterior is not null;

create index if not exists crm_suscripcion_historial_plan_nuevo_idx
  on public.crm_suscripcion_historial (id_plan_nuevo)
  where id_plan_nuevo is not null;

grant select, insert on public.crm_suscripcion_historial to authenticated;
grant usage, select on sequence public.crm_suscripcion_historial_id_seq to authenticated;
revoke all on public.crm_suscripcion_historial from anon;

drop policy if exists "crm_suscripcion_historial_company_select"
on public.crm_suscripcion_historial;
create policy "crm_suscripcion_historial_company_select"
on public.crm_suscripcion_historial for select
to authenticated
using (
  id_empresa = (select private.current_empresa_id())
  or exists (
    select 1
    from public.crm_suscripciones s
    join public.clientes_crm c on c.id = s.id_cliente_crm
    where s.id = crm_suscripcion_historial.id_suscripcion
      and c.id_auth = (select auth.uid())
  )
);

drop policy if exists "crm_suscripcion_historial_company_insert"
on public.crm_suscripcion_historial;
create policy "crm_suscripcion_historial_company_insert"
on public.crm_suscripcion_historial for insert
to authenticated
with check (
  id_empresa = (select private.current_empresa_id())
  and exists (
    select 1
    from public.crm_suscripciones s
    where s.id = crm_suscripcion_historial.id_suscripcion
      and s.id_empresa = (select private.current_empresa_id())
  )
);

create or replace function public.crm_gestionar_suscripcion(
  p_id_suscripcion bigint,
  p_accion text,
  p_id_plan bigint default null,
  p_fecha date default current_date
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $function$
declare
  v_empresa_id bigint := (select private.current_empresa_id());
  v_usuario_id bigint := (select private.current_usuario_id());
  v_suscripcion public.crm_suscripciones%rowtype;
  v_anterior public.crm_suscripciones%rowtype;
  v_plan public.crm_planes%rowtype;
  v_accion text := lower(trim(coalesce(p_accion, '')));
  v_fecha date := coalesce(p_fecha, current_date);
  v_historial_accion text;
begin
  if v_empresa_id is null then
    raise exception 'No se pudo identificar la empresa del usuario';
  end if;

  if v_accion not in ('cambiar_plan', 'renovar', 'pausar', 'reactivar', 'cancelar') then
    raise exception 'Acción de suscripción no permitida';
  end if;

  select *
  into v_suscripcion
  from public.crm_suscripciones s
  where s.id = p_id_suscripcion
    and s.id_empresa = v_empresa_id
  for update;

  if not found then
    raise exception 'No se encontró la suscripción';
  end if;

  v_anterior := v_suscripcion;

  if v_accion = 'cambiar_plan' then
    if p_id_plan is null then
      raise exception 'Selecciona el nuevo plan';
    end if;

    select *
    into v_plan
    from public.crm_planes p
    where p.id = p_id_plan
      and p.id_empresa = v_empresa_id
      and p.activo = true;

    if not found then
      raise exception 'El nuevo plan no existe o está inactivo';
    end if;

    update public.crm_suscripciones
    set
      id_plan = v_plan.id,
      fecha_inicio = v_fecha,
      fecha_fin = v_fecha + (v_plan.duracion_dias - 1),
      precio_pactado = v_plan.precio,
      estado = 'activa'
    where id = v_suscripcion.id
    returning * into v_suscripcion;

    v_historial_accion := 'cambio_plan';
  elsif v_accion = 'renovar' then
    select *
    into v_plan
    from public.crm_planes p
    where p.id = v_suscripcion.id_plan
      and p.id_empresa = v_empresa_id;

    if not found then
      raise exception 'El plan actual ya no existe';
    end if;

    update public.crm_suscripciones
    set
      fecha_fin = case
        when v_suscripcion.fecha_fin >= v_fecha
          then v_suscripcion.fecha_fin + v_plan.duracion_dias
        else v_fecha + (v_plan.duracion_dias - 1)
      end,
      precio_pactado = v_plan.precio,
      estado = 'activa'
    where id = v_suscripcion.id
    returning * into v_suscripcion;

    v_historial_accion := 'renovada';
  elsif v_accion = 'pausar' then
    update public.crm_suscripciones
    set estado = 'pausada'
    where id = v_suscripcion.id
    returning * into v_suscripcion;
    v_historial_accion := 'pausada';
  elsif v_accion = 'reactivar' then
    update public.crm_suscripciones
    set estado = 'activa'
    where id = v_suscripcion.id
    returning * into v_suscripcion;
    v_historial_accion := 'reactivada';
  else
    update public.crm_suscripciones
    set estado = 'cancelada'
    where id = v_suscripcion.id
    returning * into v_suscripcion;
    v_historial_accion := 'cancelada';
  end if;

  insert into public.crm_suscripcion_historial (
    id_empresa,
    id_suscripcion,
    accion,
    id_plan_anterior,
    id_plan_nuevo,
    fecha_inicio_anterior,
    fecha_fin_anterior,
    fecha_inicio_nueva,
    fecha_fin_nueva,
    estado_anterior,
    estado_nuevo,
    registrado_por
  )
  values (
    v_empresa_id,
    v_suscripcion.id,
    v_historial_accion,
    v_anterior.id_plan,
    v_suscripcion.id_plan,
    v_anterior.fecha_inicio,
    v_anterior.fecha_fin,
    v_suscripcion.fecha_inicio,
    v_suscripcion.fecha_fin,
    v_anterior.estado,
    v_suscripcion.estado,
    v_usuario_id
  );

  return jsonb_build_object(
    'suscripcion', to_jsonb(v_suscripcion),
    'accion', v_historial_accion
  );
end;
$function$;

revoke all on function public.crm_gestionar_suscripcion(bigint, text, bigint, date)
from public, anon;
grant execute on function public.crm_gestionar_suscripcion(bigint, text, bigint, date)
to authenticated;

create or replace function public.crm_facturar_suscripcion(
  p_id_suscripcion bigint,
  p_estado text default 'pagado',
  p_metodo_pago text default null,
  p_notas text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $function$
declare
  v_empresa_id bigint := (select private.current_empresa_id());
  v_usuario_id bigint := (select private.current_usuario_id());
  v_suscripcion public.crm_suscripciones%rowtype;
  v_cliente public.clientes_crm%rowtype;
  v_plan public.crm_planes%rowtype;
  v_pago public.crm_pagos%rowtype;
  v_moneda text;
begin
  if v_empresa_id is null then
    raise exception 'No se pudo identificar la empresa del usuario';
  end if;

  if p_estado not in ('pendiente', 'pagado', 'vencido') then
    raise exception 'Estado de factura no permitido';
  end if;

  select *
  into v_suscripcion
  from public.crm_suscripciones s
  where s.id = p_id_suscripcion
    and s.id_empresa = v_empresa_id;

  if not found then
    raise exception 'La suscripción no pertenece a la empresa actual';
  end if;

  select * into v_cliente
  from public.clientes_crm c
  where c.id = v_suscripcion.id_cliente_crm
    and c.id_empresa = v_empresa_id;

  select * into v_plan
  from public.crm_planes p
  where p.id = v_suscripcion.id_plan
    and p.id_empresa = v_empresa_id;

  select coalesce(currency, 'USD')
  into v_moneda
  from public.empresa
  where id = v_empresa_id;

  insert into public.crm_pagos (
    id_empresa,
    id_cliente_crm,
    id_suscripcion,
    monto,
    moneda,
    metodo_pago,
    fecha_pago,
    fecha_vencimiento,
    periodo_inicio,
    periodo_fin,
    estado,
    registrado_por,
    notas
  )
  values (
    v_empresa_id,
    v_cliente.id,
    v_suscripcion.id,
    v_suscripcion.precio_pactado,
    coalesce(v_moneda, 'USD'),
    nullif(trim(p_metodo_pago), ''),
    case when p_estado = 'pagado' then now() else null end,
    v_suscripcion.fecha_fin,
    v_suscripcion.fecha_inicio,
    v_suscripcion.fecha_fin,
    p_estado,
    v_usuario_id,
    nullif(trim(p_notas), '')
  )
  returning * into v_pago;

  update public.crm_pagos
  set referencia = format(
    'FAC-%s-%s-%s',
    v_empresa_id,
    to_char(coalesce(v_pago.fecha_pago, v_pago.created_at), 'YYYY'),
    lpad(v_pago.id::text, 6, '0')
  )
  where id = v_pago.id
  returning * into v_pago;

  return jsonb_build_object(
    'cliente', to_jsonb(v_cliente),
    'plan', to_jsonb(v_plan),
    'suscripcion', to_jsonb(v_suscripcion),
    'pago', to_jsonb(v_pago)
  );
end;
$function$;

revoke all on function public.crm_facturar_suscripcion(bigint, text, text, text)
from public, anon;
grant execute on function public.crm_facturar_suscripcion(bigint, text, text, text)
to authenticated;

create or replace function public.crm_asignar_horario_cliente(
  p_id_cliente_crm bigint,
  p_id_horario bigint default null
)
returns public.clientes_crm
language plpgsql
security invoker
set search_path = ''
as $function$
declare
  v_empresa_id bigint := (select private.current_empresa_id());
  v_cliente public.clientes_crm%rowtype;
begin
  if v_empresa_id is null then
    raise exception 'No se pudo identificar la empresa del usuario';
  end if;

  if p_id_horario is not null and not exists (
    select 1
    from public.crm_horarios h
    where h.id = p_id_horario
      and h.id_empresa = v_empresa_id
      and h.activo = true
  ) then
    raise exception 'El horario no existe o está inactivo';
  end if;

  update public.clientes_crm
  set id_horario = p_id_horario
  where id = p_id_cliente_crm
    and id_empresa = v_empresa_id
  returning * into v_cliente;

  if not found then
    raise exception 'No se encontró el cliente';
  end if;

  return v_cliente;
end;
$function$;

revoke all on function public.crm_asignar_horario_cliente(bigint, bigint)
from public, anon;
grant execute on function public.crm_asignar_horario_cliente(bigint, bigint)
to authenticated;

create or replace function public.crm_registrar_asistencia(
  p_id_cliente_crm bigint,
  p_estado text,
  p_id_horario bigint default null,
  p_notas text default null
)
returns public.crm_asistencias
language plpgsql
security invoker
set search_path = ''
as $function$
declare
  v_empresa_id bigint := (select private.current_empresa_id());
  v_usuario_id bigint := (select private.current_usuario_id());
  v_cliente public.clientes_crm%rowtype;
  v_asistencia public.crm_asistencias%rowtype;
  v_estado text := lower(trim(coalesce(p_estado, '')));
  v_horario_id bigint;
begin
  if v_empresa_id is null then
    raise exception 'No se pudo identificar la empresa del usuario';
  end if;

  if v_estado not in ('presente', 'tarde', 'ausente', 'salida_registrada') then
    raise exception 'Estado de asistencia no permitido';
  end if;

  select *
  into v_cliente
  from public.clientes_crm c
  where c.id = p_id_cliente_crm
    and c.id_empresa = v_empresa_id
  for update;

  if not found then
    raise exception 'No se encontró el cliente';
  end if;

  v_horario_id := coalesce(p_id_horario, v_cliente.id_horario);

  if v_horario_id is not null and not exists (
    select 1
    from public.crm_horarios h
    where h.id = v_horario_id
      and h.id_empresa = v_empresa_id
      and h.activo = true
  ) then
    raise exception 'El horario no existe o está inactivo';
  end if;

  if p_id_horario is not null and p_id_horario is distinct from v_cliente.id_horario then
    update public.clientes_crm
    set id_horario = p_id_horario
    where id = v_cliente.id;
  end if;

  if v_estado = 'salida_registrada' and not exists (
    select 1
    from public.crm_asistencias a
    where a.id_empresa = v_empresa_id
      and a.id_cliente_crm = v_cliente.id
      and a.fecha = current_date
      and a.hora_entrada is not null
  ) then
    raise exception 'Primero registra la entrada del cliente';
  end if;

  insert into public.crm_asistencias (
    id_empresa,
    id_cliente_crm,
    id_horario,
    fecha,
    hora_entrada,
    hora_salida,
    estado,
    registrado_por,
    notas
  )
  values (
    v_empresa_id,
    v_cliente.id,
    v_horario_id,
    current_date,
    case when v_estado in ('presente', 'tarde') then now() else null end,
    case when v_estado = 'salida_registrada' then now() else null end,
    v_estado,
    v_usuario_id,
    nullif(trim(p_notas), '')
  )
  on conflict (id_empresa, id_cliente_crm, fecha)
  do update set
    id_horario = coalesce(excluded.id_horario, crm_asistencias.id_horario),
    hora_entrada = case
      when excluded.estado in ('presente', 'tarde')
        then coalesce(crm_asistencias.hora_entrada, excluded.hora_entrada)
      when excluded.estado = 'ausente' then null
      else crm_asistencias.hora_entrada
    end,
    hora_salida = case
      when excluded.estado = 'salida_registrada' then now()
      when excluded.estado in ('presente', 'tarde', 'ausente') then null
      else crm_asistencias.hora_salida
    end,
    estado = excluded.estado,
    registrado_por = excluded.registrado_por,
    notas = coalesce(excluded.notas, crm_asistencias.notas)
  returning * into v_asistencia;

  return v_asistencia;
end;
$function$;

revoke all on function public.crm_registrar_asistencia(bigint, text, bigint, text)
from public, anon;
grant execute on function public.crm_registrar_asistencia(bigint, text, bigint, text)
to authenticated;

create or replace view public.crm_clientes_asistencia
with (security_invoker = true)
as
select
  c.id,
  c.public_id,
  c.id_empresa,
  c.codigo,
  c.nombres,
  c.apellidos,
  trim(concat_ws(' ', c.nombres, c.apellidos)) as cliente_nombre,
  c.email,
  c.telefono,
  c.estado as cliente_estado,
  c.id_horario,
  h.nombre as horario_nombre,
  h.hora_entrada as horario_entrada,
  h.hora_salida as horario_salida,
  h.dias_semana as horario_dias_semana,
  h.tolerancia_minutos as horario_tolerancia_minutos,
  a.id as asistencia_id,
  a.fecha as asistencia_fecha,
  a.estado as asistencia_estado,
  a.hora_entrada as asistencia_hora_entrada,
  a.hora_salida as asistencia_hora_salida,
  s.id as suscripcion_id,
  s.estado as suscripcion_estado,
  s.fecha_fin as suscripcion_fecha_fin,
  p.nombre as plan_nombre,
  lower(concat_ws(
    ' ',
    c.codigo,
    c.nombres,
    c.apellidos,
    c.email,
    c.telefono
  )) as busqueda
from public.clientes_crm c
left join public.crm_horarios h
  on h.id = c.id_horario
 and h.id_empresa = c.id_empresa
left join lateral (
  select attendance.*
  from public.crm_asistencias attendance
  where attendance.id_empresa = c.id_empresa
    and attendance.id_cliente_crm = c.id
    and attendance.fecha = current_date
  order by attendance.updated_at desc, attendance.id desc
  limit 1
) a on true
left join lateral (
  select subscription.*
  from public.crm_suscripciones subscription
  where subscription.id_empresa = c.id_empresa
    and subscription.id_cliente_crm = c.id
  order by
    (subscription.estado = 'activa') desc,
    subscription.fecha_fin desc,
    subscription.id desc
  limit 1
) s on true
left join public.crm_planes p
  on p.id = s.id_plan
 and p.id_empresa = s.id_empresa;

revoke all on public.crm_clientes_asistencia from public, anon;
grant select on public.crm_clientes_asistencia to authenticated;

-- The implementation needs elevated rights only because invitation recipients
-- are not staff rows yet. It validates auth.uid + auth email before every write.
create or replace function private.crm_completar_invitacion_impl(
  p_invitacion_id uuid,
  p_nombres text,
  p_apellidos text default null,
  p_telefono text default null,
  p_direccion text default null,
  p_identificador_nacional text default null,
  p_identificador_fiscal text default null,
  p_fecha_nacimiento date default null,
  p_notas text default null
)
returns public.clientes_crm
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_invitacion public.crm_invitaciones%rowtype;
  v_cliente public.clientes_crm%rowtype;
  v_plan public.crm_planes%rowtype;
  v_suscripcion public.crm_suscripciones%rowtype;
  v_auth_id uuid := (select auth.uid());
  v_auth_email text := lower((select auth.jwt() ->> 'email'));
begin
  if v_auth_id is null or nullif(v_auth_email, '') is null then
    raise exception 'Debes abrir la invitación con el correo autenticado';
  end if;
  if nullif(trim(p_nombres), '') is null then
    raise exception 'El nombre es obligatorio';
  end if;

  select *
  into v_invitacion
  from public.crm_invitaciones i
  where i.id = p_invitacion_id
    and i.estado = 'pendiente'
    and i.expires_at > now()
    and lower(i.email) = v_auth_email
  for update;

  if not found then
    raise exception 'La invitación no está disponible o ya venció';
  end if;

  if v_invitacion.id_plan is null then
    raise exception 'La invitación no tiene un plan asignado';
  end if;

  select *
  into v_plan
  from public.crm_planes p
  where p.id = v_invitacion.id_plan
    and p.id_empresa = v_invitacion.id_empresa
    and p.activo = true;

  if not found then
    raise exception 'El plan de la invitación ya no está disponible';
  end if;

  select *
  into v_cliente
  from public.clientes_crm c
  where c.id_empresa = v_invitacion.id_empresa
    and lower(c.email) = v_auth_email
  limit 1
  for update;

  if found then
    if v_cliente.id_auth is not null and v_cliente.id_auth <> v_auth_id then
      raise exception 'El correo ya está vinculado a otro cliente';
    end if;

    update public.clientes_crm
    set
      id_auth = v_auth_id,
      nombres = trim(p_nombres),
      apellidos = nullif(trim(p_apellidos), ''),
      telefono = nullif(trim(p_telefono), ''),
      direccion = nullif(trim(p_direccion), ''),
      identificador_nacional = nullif(trim(p_identificador_nacional), ''),
      identificador_fiscal = nullif(trim(p_identificador_fiscal), ''),
      fecha_nacimiento = p_fecha_nacimiento,
      notas = nullif(trim(p_notas), ''),
      estado = 'activo',
      origen = 'invitacion'
    where id = v_cliente.id
    returning * into v_cliente;
  else
    insert into public.clientes_crm (
      id_empresa,
      id_auth,
      nombres,
      apellidos,
      email,
      telefono,
      direccion,
      identificador_nacional,
      identificador_fiscal,
      fecha_nacimiento,
      estado,
      origen,
      notas
    )
    values (
      v_invitacion.id_empresa,
      v_auth_id,
      trim(p_nombres),
      nullif(trim(p_apellidos), ''),
      v_auth_email,
      nullif(trim(p_telefono), ''),
      nullif(trim(p_direccion), ''),
      nullif(trim(p_identificador_nacional), ''),
      nullif(trim(p_identificador_fiscal), ''),
      p_fecha_nacimiento,
      'activo',
      'invitacion',
      nullif(trim(p_notas), '')
    )
    returning * into v_cliente;
  end if;

  if v_cliente.codigo is null or btrim(v_cliente.codigo) = '' then
    update public.clientes_crm
    set codigo = 'CLI-' || lpad(v_cliente.id::text, 6, '0')
    where id = v_cliente.id
    returning * into v_cliente;
  end if;

  select *
  into v_suscripcion
  from public.crm_suscripciones s
  where s.id_empresa = v_invitacion.id_empresa
    and s.id_cliente_crm = v_cliente.id
    and s.estado in ('activa', 'pausada')
  order by s.created_at desc, s.id desc
  limit 1
  for update;

  if found then
    update public.crm_suscripciones
    set
      id_plan = v_plan.id,
      fecha_inicio = current_date,
      fecha_fin = current_date + (v_plan.duracion_dias - 1),
      precio_pactado = v_plan.precio,
      estado = 'activa'
    where id = v_suscripcion.id
    returning * into v_suscripcion;
  else
    insert into public.crm_suscripciones (
      id_empresa,
      id_cliente_crm,
      id_plan,
      fecha_inicio,
      fecha_fin,
      precio_pactado,
      estado
    )
    values (
      v_invitacion.id_empresa,
      v_cliente.id,
      v_plan.id,
      current_date,
      current_date + (v_plan.duracion_dias - 1),
      v_plan.precio,
      'activa'
    )
    returning * into v_suscripcion;
  end if;

  insert into public.crm_suscripcion_historial (
    id_empresa,
    id_suscripcion,
    accion,
    id_plan_nuevo,
    fecha_inicio_nueva,
    fecha_fin_nueva,
    estado_nuevo,
    detalle
  )
  values (
    v_invitacion.id_empresa,
    v_suscripcion.id,
    'invitacion_aceptada',
    v_plan.id,
    v_suscripcion.fecha_inicio,
    v_suscripcion.fecha_fin,
    v_suscripcion.estado,
    jsonb_build_object('invitacion_id', v_invitacion.id)
  );

  update public.crm_invitaciones
  set
    estado = 'aceptada',
    accepted_at = now(),
    id_cliente_crm = v_cliente.id
  where id = v_invitacion.id;

  return v_cliente;
end;
$function$;

revoke all on function private.crm_completar_invitacion_impl(
  uuid, text, text, text, text, text, text, date, text
) from public, anon;
grant execute on function private.crm_completar_invitacion_impl(
  uuid, text, text, text, text, text, text, date, text
) to authenticated;

create or replace function public.crm_completar_invitacion(
  p_invitacion_id uuid,
  p_nombres text,
  p_apellidos text default null,
  p_telefono text default null,
  p_direccion text default null,
  p_identificador_nacional text default null,
  p_identificador_fiscal text default null,
  p_fecha_nacimiento date default null,
  p_notas text default null
)
returns public.clientes_crm
language sql
security invoker
set search_path = ''
as $function$
  select private.crm_completar_invitacion_impl(
    p_invitacion_id,
    p_nombres,
    p_apellidos,
    p_telefono,
    p_direccion,
    p_identificador_nacional,
    p_identificador_fiscal,
    p_fecha_nacimiento,
    p_notas
  )
$function$;

revoke all on function public.crm_completar_invitacion(
  uuid, text, text, text, text, text, text, date, text
) from public, anon;
grant execute on function public.crm_completar_invitacion(
  uuid, text, text, text, text, text, text, date, text
) to authenticated;

notify pgrst, 'reload schema';
