-- Persisted CRM receipts make debt settlements auditable and reprintable.
create table if not exists public.crm_comprobantes_cobro (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresa(id) on delete cascade,
  id_cliente_crm bigint not null references public.clientes_crm(id) on delete cascade,
  id_suscripcion bigint references public.crm_suscripciones(id) on delete set null,
  referencia text,
  monto numeric(12,2) not null check (monto > 0),
  monto_recibido numeric(12,2),
  cambio numeric(12,2) not null default 0 check (cambio >= 0),
  moneda text not null default 'USD',
  metodo_pago text not null,
  referencia_pago text,
  fecha_pago timestamptz not null default now(),
  notas text,
  pagos_liquidados jsonb not null default '[]'::jsonb,
  registrado_por bigint references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_empresa, referencia)
);

create index if not exists crm_comprobantes_cobro_empresa_fecha_idx
  on public.crm_comprobantes_cobro (id_empresa, fecha_pago desc);

alter table public.crm_comprobantes_cobro enable row level security;
grant select, insert, update, delete on public.crm_comprobantes_cobro to authenticated;
grant usage, select on sequence public.crm_comprobantes_cobro_id_seq to authenticated;
revoke all on public.crm_comprobantes_cobro from anon;

create policy "crm_comprobantes_cobro_company_select"
on public.crm_comprobantes_cobro for select to authenticated
using (id_empresa = (select private.current_empresa_id()));

create policy "crm_comprobantes_cobro_company_write"
on public.crm_comprobantes_cobro for all to authenticated
using (id_empresa = (select private.current_empresa_id()))
with check (id_empresa = (select private.current_empresa_id()));

drop trigger if exists trg_crm_comprobantes_cobro_updated_at on public.crm_comprobantes_cobro;
create trigger trg_crm_comprobantes_cobro_updated_at
before update on public.crm_comprobantes_cobro
for each row execute function private.set_updated_at();

-- Preserve the receipt for debt settlements created before this table existed.
insert into public.crm_comprobantes_cobro (
  id_empresa, id_cliente_crm, referencia, monto, monto_recibido, cambio,
  moneda, metodo_pago, referencia_pago, fecha_pago, notas, pagos_liquidados, registrado_por
)
select
  payment.id_empresa,
  payment.id_cliente_crm,
  payment.referencia_pago,
  sum(payment.monto)::numeric(12,2),
  greatest(max(payment.monto_recibido), sum(payment.monto))::numeric(12,2),
  max(payment.cambio)::numeric(12,2),
  max(payment.moneda),
  max(payment.metodo_pago),
  payment.referencia_pago,
  min(payment.fecha_pago),
  'Pago de saldo vencido',
  jsonb_agg(payment.id order by payment.id),
  max(payment.registrado_por)
from public.crm_pagos payment
where payment.estado = 'pagado'
  and payment.referencia_pago like 'REC-MORA-%'
group by payment.id_empresa, payment.id_cliente_crm, payment.referencia_pago
on conflict (id_empresa, referencia) do nothing;

create or replace view public.crm_historial_cobros
with (security_invoker = true)
as
select
  concat('P-', payment.id) as id,
  'pago'::text as origen,
  payment.id as id_origen,
  payment.id_empresa,
  payment.id_cliente_crm,
  payment.id_suscripcion,
  payment.referencia,
  payment.monto,
  payment.monto_recibido,
  payment.cambio,
  payment.moneda,
  payment.metodo_pago,
  payment.referencia_pago,
  payment.fecha_pago,
  payment.fecha_vencimiento,
  payment.periodo_inicio,
  payment.periodo_fin,
  payment.estado,
  payment.notas,
  client.nombres as cliente_nombres,
  client.apellidos as cliente_apellidos,
  client.email as cliente_email,
  client.telefono as cliente_telefono,
  client.direccion as cliente_direccion,
  client.identificador_fiscal as cliente_identificador_fiscal,
  client.identificador_nacional as cliente_identificador_nacional,
  plan.nombre as plan_nombre,
  plan.descripcion as plan_descripcion,
  subscription.fecha_inicio as suscripcion_inicio,
  subscription.fecha_fin as suscripcion_fin,
  lower(concat_ws(' ', payment.referencia, payment.referencia_pago, client.nombres, client.apellidos, client.email, plan.nombre)) as busqueda
from public.crm_pagos payment
join public.clientes_crm client on client.id = payment.id_cliente_crm
left join public.crm_suscripciones subscription on subscription.id = payment.id_suscripcion
left join public.crm_planes plan on plan.id = subscription.id_plan
where payment.estado = 'pagado'
  and coalesce(payment.referencia_pago, '') not like 'REC-MORA-%'
union all
select
  concat('R-', receipt.id) as id,
  'recibo_mora'::text as origen,
  receipt.id as id_origen,
  receipt.id_empresa,
  receipt.id_cliente_crm,
  receipt.id_suscripcion,
  receipt.referencia,
  receipt.monto,
  receipt.monto_recibido,
  receipt.cambio,
  receipt.moneda,
  receipt.metodo_pago,
  receipt.referencia_pago,
  receipt.fecha_pago,
  receipt.fecha_pago::date as fecha_vencimiento,
  subscription.fecha_inicio as periodo_inicio,
  subscription.fecha_fin as periodo_fin,
  'pagado'::text as estado,
  receipt.notas,
  client.nombres as cliente_nombres,
  client.apellidos as cliente_apellidos,
  client.email as cliente_email,
  client.telefono as cliente_telefono,
  client.direccion as cliente_direccion,
  client.identificador_fiscal as cliente_identificador_fiscal,
  client.identificador_nacional as cliente_identificador_nacional,
  plan.nombre as plan_nombre,
  plan.descripcion as plan_descripcion,
  subscription.fecha_inicio as suscripcion_inicio,
  subscription.fecha_fin as suscripcion_fin,
  lower(concat_ws(' ', receipt.referencia, receipt.referencia_pago, client.nombres, client.apellidos, client.email, plan.nombre)) as busqueda
from public.crm_comprobantes_cobro receipt
join public.clientes_crm client on client.id = receipt.id_cliente_crm
left join public.crm_suscripciones subscription on subscription.id = receipt.id_suscripcion
left join public.crm_planes plan on plan.id = subscription.id_plan;

revoke all on public.crm_historial_cobros from public, anon;
grant select on public.crm_historial_cobros to authenticated;

create or replace function public.crm_cobrar_mora_pos(
  p_id_cliente_crm bigint,
  p_metodo_pago text default 'efectivo',
  p_monto_recibido numeric default null,
  p_referencia_pago text default null,
  p_notas text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $function$
declare
  v_empresa_id bigint := (select private.current_empresa_id());
  v_usuario_id bigint := (select private.current_usuario_id());
  v_cliente public.clientes_crm%rowtype;
  v_plan public.crm_planes%rowtype;
  v_suscripcion public.crm_suscripciones%rowtype;
  v_comprobante public.crm_comprobantes_cobro%rowtype;
  v_moneda text;
  v_metodo text := lower(nullif(trim(coalesce(p_metodo_pago, '')), ''));
  v_total numeric(12,2);
  v_recibido numeric(12,2);
  v_cambio numeric(12,2) := 0;
  v_facturas integer;
  v_referencia text;
  v_ids jsonb;
begin
  if v_empresa_id is null or v_usuario_id is null then
    raise exception 'No se pudo identificar la empresa o el usuario';
  end if;
  if v_metodo not in ('efectivo', 'transferencia', 'tarjeta', 'deposito', 'otro') then
    raise exception 'Selecciona un método de pago válido';
  end if;
  if v_metodo in ('transferencia', 'deposito') and nullif(trim(p_referencia_pago), '') is null then
    raise exception 'La transferencia o depósito requiere número de referencia';
  end if;
  select * into v_cliente from public.clientes_crm client
  where client.id = p_id_cliente_crm and client.id_empresa = v_empresa_id;
  if not found then raise exception 'El cliente no pertenece a la empresa actual'; end if;

  perform 1 from public.crm_pagos payment
  where payment.id_empresa = v_empresa_id and payment.id_cliente_crm = v_cliente.id
    and (payment.estado = 'vencido' or (payment.estado = 'pendiente' and payment.fecha_vencimiento < current_date))
  for update;
  select coalesce(sum(payment.monto), 0)::numeric(12,2), count(*)::integer, jsonb_agg(payment.id order by payment.id)
  into v_total, v_facturas, v_ids
  from public.crm_pagos payment
  where payment.id_empresa = v_empresa_id and payment.id_cliente_crm = v_cliente.id
    and (payment.estado = 'vencido' or (payment.estado = 'pendiente' and payment.fecha_vencimiento < current_date));
  if v_total <= 0 or v_facturas = 0 then
    raise exception 'El cliente no tiene saldo vencido por cobrar';
  end if;
  v_recibido := case when v_metodo = 'efectivo' then round(coalesce(p_monto_recibido, v_total), 2) else v_total end;
  if v_metodo = 'efectivo' and v_recibido < v_total then
    raise exception 'El efectivo recibido no cubre el saldo vencido';
  end if;
  if v_metodo = 'efectivo' then v_cambio := v_recibido - v_total; end if;

  select * into v_suscripcion from public.crm_suscripciones subscription
  where subscription.id_empresa = v_empresa_id and subscription.id_cliente_crm = v_cliente.id
  order by subscription.fecha_fin desc, subscription.id desc limit 1;
  if found then select * into v_plan from public.crm_planes plan where plan.id = v_suscripcion.id_plan; end if;
  select coalesce(currency, 'USD') into v_moneda from public.empresa where id = v_empresa_id;
  insert into public.crm_comprobantes_cobro (
    id_empresa, id_cliente_crm, id_suscripcion, monto, monto_recibido, cambio, moneda,
    metodo_pago, referencia_pago, notas, pagos_liquidados, registrado_por
  ) values (
    v_empresa_id, v_cliente.id, v_suscripcion.id, v_total, v_recibido, v_cambio, coalesce(v_moneda, 'USD'),
    initcap(v_metodo), nullif(trim(p_referencia_pago), ''),
    coalesce(nullif(trim(p_notas), ''), format('Pago de %s documento(s) vencido(s)', v_facturas)), v_ids, v_usuario_id
  ) returning * into v_comprobante;
  v_referencia := format('REC-MORA-%s-%s-%s', v_empresa_id, to_char(v_comprobante.fecha_pago, 'YYYY'), lpad(v_comprobante.id::text, 6, '0'));
  update public.crm_comprobantes_cobro set referencia = v_referencia where id = v_comprobante.id returning * into v_comprobante;

  update public.crm_pagos payment
  set estado = 'pagado', fecha_pago = now(), metodo_pago = initcap(v_metodo), referencia_pago = v_referencia,
      notas = coalesce(nullif(trim(p_notas), ''), 'Pago de saldo vencido'),
      monto_recibido = case when payment.id = (v_ids->>0)::bigint then v_recibido else payment.monto end,
      cambio = case when payment.id = (v_ids->>0)::bigint then v_cambio else 0 end
  where payment.id_empresa = v_empresa_id and payment.id = any (select jsonb_array_elements_text(v_ids)::bigint);

  return jsonb_build_object(
    'cliente', to_jsonb(v_cliente), 'plan', case when v_plan.id is null then null else to_jsonb(v_plan) end,
    'suscripcion', case when v_suscripcion.id is null then null else to_jsonb(v_suscripcion) end,
    'pago', to_jsonb(v_comprobante), 'facturas_liquidadas', v_facturas, 'saldo_cobrado', v_total
  );
end;
$function$;

revoke all on function public.crm_cobrar_mora_pos(bigint, text, numeric, text, text) from public, anon;
grant execute on function public.crm_cobrar_mora_pos(bigint, text, numeric, text, text) to authenticated;
